/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by tauri-specta. DO NOT EDIT.
// Source: src-tauri/src/lib.rs::build_specta_builder.
// Regenerate (Linux/macOS): `cd src-tauri && cargo test --features codegen --test specta_codegen generate_bindings_ts`.
// Regenerate (Windows):     `cd src-tauri && MDOWNREVIEW_GEN_BINDINGS_ONLY=1 cargo run --features codegen`.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Read directory entries, rejecting path traversal.
 * Returns at most `limit` entries (default 250) with total count so the
 * frontend can offer a "Show all N items…" affordance.
 * Hides `.review.yaml`/`.review.json` sidecar files, and also hides the
 * `sidecar_root` directory when listing a workspace root with an active
 * redirect (AC10: prevents users from seeing the internal sidecar store).
 */
async readDir(path: string, limit: number | null, showSidecars: boolean | null) : Promise<Result<ReadDirResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_dir", { path, limit, showSidecars }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a text file, rejecting binary files and files >10 MB.
 * 
 * Returns the decoded UTF-8 content alongside `size_bytes` (raw byte length
 * of the on-disk file), `line_count` (logical lines as defined by
 * [`str::lines`]), and `mtime_ms` (last-modified epoch ms; `None` when the
 * platform/FS does not expose it). The file handle's metadata is read
 * before the body so content + mtime come from the same `open()` and the
 * caller cannot observe a torn (content_v1, mtime_v2) pair.
 */
async readTextFile(path: string) : Promise<Result<TextFileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_text_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a binary file, returning base64-encoded content. Rejects files >10 MB.
 */
async readBinaryFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_binary_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async statFile(path: string) : Promise<Result<FileStat, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stat_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the OS file manager and select the file at `path`.
 * 
 * Workspace-allowlisted via `WatcherState::is_path_allowed`. On Linux there
 * is no portable "select" — we open the parent directory instead.
 */
async revealInFolder(path: string) : Promise<Result<null, SystemError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inline local images as data URIs and stylesheets as `<style>` blocks.
 * Replaces the previous TS implementation in `src/lib/resolve-html-assets.ts`.
 * Per-asset failures preserve the original tag (graceful fallback).
 */
async resolveHtmlAssets(html: string, htmlDir: string) : Promise<string> {
    return await TAURI_INVOKE("resolve_html_assets", { html, htmlDir });
},
/**
 * Get (and drain) launch args queued for the calling window.
 */
async getLaunchArgs() : Promise<Result<LaunchArgs, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_launch_args") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the log file path for display in the About dialog.
 */
async getLogPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory tree for MRSF sidecar files (delegates to core::scanner).
 * 
 * Honours the workspace's `.mrsf.yaml` redirect so sidecars stored
 * under e.g. `.reviews/` are mapped back to their real source location
 * instead of being incorrectly flagged as ghosts. Both the GUI IPC
 * and the CLI go through [`crate::core::scanner::scan_workspace`] for
 * identical `(sidecar, source)` output.
 */
async scanReviewFiles(root: string) : Promise<Result<([string, string])[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_review_files", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a path exists and whether it is a directory or file.
 */
async checkPathExists(path: string) : Promise<PathKind> {
    return await TAURI_INVOKE("check_path_exists", { path });
},
/**
 * Canonicalize an absolute path to the long form without the Windows `\\?\`
 * verbatim prefix. Used by the renderer to normalize paths at workspace-open
 * and tab-open boundaries so that string-equality comparisons against
 * scanner output (which itself canonicalizes via `dunce`) match. No
 * workspace guard — this is the very command callers use to obtain the
 * canonical form before they have a workspace to validate against.
 */
async canonicalizePath(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("canonicalize_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Combined hot-path: load sidecar → match to file lines → build threads.
 * Single IPC call for the GUI's most common operation.
 * 
 * Comments are partitioned by anchor variant: `Line`/`File` go through the
 * existing `match_comments` batch algorithm (line-targeting heuristics);
 * typed anchors (CSV cell, JSON path, HTML range/element, image rect,
 * word range) are dispatched through [`crate::core::anchors::resolve_anchor`]
 * against a single shared [`crate::core::anchors::LazyParsedDoc`] so the
 * file is parsed at most once per call (lazily, only for the
 * representations the present anchors actually need).
 * 
 * Workspace-allowlisted via [`enforce_workspace_path`] (advisory #5 / iter-4
 * security blocker S2): rejects paths the user has not opened so a renderer
 * cannot probe arbitrary files. The file body itself is read with a 10 MB
 * cap (matching `read_text_file` and `SIDECAR_MAX_BYTES`) — anything larger
 * degrades silently to empty bytes so all comments orphan, identical to the
 * `NotFound` branch.
 */
async getFileComments(filePath: string) : Promise<Result<GetFileCommentsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_comments", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new comment, save to sidecar.
 * 
 * `clippy::too_many_arguments` is intentionally permitted here: this is a
 * `#[tauri::command]`, so its parameter list is the IPC wire shape consumed
 * by `invoke("add_comment", { ... })` on the JS side. Grouping arguments
 * into a struct would change the wire contract.
 */
async addComment(filePath: string, author: string, text: string, anchor: NewCommentAnchor | null, commentType: string | null, severity: string | null, document: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_comment", { filePath, author, text, anchor, commentType, severity, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a reply to an existing comment, save to sidecar.
 */
async addReply(filePath: string, parentId: string, author: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_reply", { filePath, parentId, author, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a comment's text, save to sidecar.
 */
async editComment(filePath: string, commentId: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_comment", { filePath, commentId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a comment (with reply reparenting per MRSF §9.1), save to sidecar.
 */
async deleteComment(filePath: string, commentId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_comment", { filePath, commentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compute SHA-256 hash for selected text anchor.
 */
async computeAnchorHash(text: string) : Promise<string> {
    return await TAURI_INVOKE("compute_anchor_hash", { text });
},
/**
 * Apply a [`CommentPatch`] to a single comment.
 */
async updateComment(filePath: string, commentId: string, patch: CommentPatch) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_comment", { filePath, commentId, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-file unresolved-thread count + worst severity.
 */
async getFileBadges(filePaths: string[]) : Promise<Result<Partial<{ [key in string]: FileBadge }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_badges", { filePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAuthor(name: string) : Promise<Result<string, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_author", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAuthor() : Promise<Result<string, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_author") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchInDocument(content: string, query: string) : Promise<SearchMatch[]> {
    return await TAURI_INVOKE("search_in_document", { content, query });
},
async computeFoldRegions(content: string, language: string) : Promise<FoldRegion[]> {
    return await TAURI_INVOKE("compute_fold_regions", { content, language });
},
async parseKql(query: string) : Promise<KqlPipelineStep[]> {
    return await TAURI_INVOKE("parse_kql", { query });
},
async stripJsonComments(text: string) : Promise<string> {
    return await TAURI_INVOKE("strip_json_comments", { text });
},
async onboardingState() : Promise<Result<OnboardingState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cliShimStatus() : Promise<CliShimStatus> {
    return await TAURI_INVOKE("cli_shim_status");
},
async installCliShim() : Promise<Result<null, CliShimError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_cli_shim") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCliShim() : Promise<Result<null, CliShimError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_cli_shim") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async defaultHandlerStatus() : Promise<DefaultHandlerStatus> {
    return await TAURI_INVOKE("default_handler_status");
},
async setDefaultHandler() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_handler") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileViewerPref(path: string) : Promise<FileViewerPref | null> {
    return await TAURI_INVOKE("get_file_viewer_pref", { path });
},
async setFileViewerPref(path: string, allowImages: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_file_viewer_pref", { path, allowImages }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: update the set of watched file paths.
 * The frontend calls this whenever the set of open tabs changes.
 */
async updateWatchedFiles(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_watched_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the set of directories whose direct children should produce
 * `folder-changed` events (root + currently-expanded folders in the tree pane).
 * 
 * `root` and every entry in `dirs` are canonicalized internally; callers may
 * pass any absolute form. Each entry must exist and be a directory, and every
 * dir must be contained within `root`. At most
 * [`crate::watcher::MAX_TREE_WATCHED_DIRS`] entries per call.
 * 
 * Also loads the `.mrsf.yaml` config for the workspace root and caches
 * its `sidecar_root` value in [`SidecarConfigState`] so that subsequent
 * sidecar reads/writes use the configured path.
 */
async updateTreeWatchedDirs(root: string, dirs: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tree_watched_dirs", { root, dirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tokenizeWords(text: string) : Promise<Result<WordSpan[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tokenize_words", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSidecarConfig(root: string) : Promise<Result<SidecarConfigResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sidecar_config", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSidecarConfig(root: string, enabled: boolean) : Promise<Result<SidecarConfigResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sidecar_config", { root, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async migrateSidecarsCmd(root: string, direction: MigrateDirection) : Promise<Result<MigrateSidecarsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("migrate_sidecars_cmd", { root, direction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check for an update on the given channel.
 * For cross-channel switches the version comparator is overridden
 * to accept any different version (enabling "downgrades").
 */
async checkUpdate(channel: string) : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and install the pending update. Emits "update-progress"
 * events so the frontend can show a progress bar.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerWindowFolder(folder: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_window_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterWindowFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_window_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test-only command: open a folder and all its non-sidecar files via args-received.
 */
async setRootViaTest(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_root_via_test", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Specta-shadow for [`AnchorRepr`]. Mirrors the wire JSON shape
 * (`{anchor_kind, anchor_data}`) emitted by the hand-rolled serde
 * impls below. Used only for TS codegen; never (de)serialised at
 * runtime. Iter 2 may sharpen `anchor_data` into a discriminated
 * union for better TS ergonomics.
 * 
 * Referenced exclusively via field-level `#[specta(type = AnchorWire)]`
 * forwarding on every public struct that names `Anchor` or
 * `AnchorRepr` (see `Anchor` in `mod.rs` and `MrsfCommentRepr`'s
 * `anchor_history` field). `AnchorRepr` itself does NOT derive
 * `specta::Type` because the hand-rolled `Serialize` / `Deserialize`
 * impls below produce a shape that the natural enum-derive cannot
 * describe accurately.
 */
export type AnchorWire = { anchor_kind: string; anchor_data: JsonValue }
/**
 * Structured error for CLI-shim install/remove. Serializes to a tagged
 * payload (`{"kind":"...", ...}`) so the FE can branch on `kind` without
 * string matching. Manual `Display` impl avoids pulling in `thiserror`.
 */
export type CliShimError = { kind: "permission_denied"; path: string; target: string } | { kind: "io"; message: string }
export type CliShimStatus = "done" | "missing" | "broken" | "unsupported"
/**
 * Anchor specification for creating new comments.
 */
export type CommentAnchor = { line: number; end_line?: number | null; start_column?: number | null; end_column?: number | null; selected_text?: string | null; selected_text_hash?: string | null }
/**
 * Patch payloads for `update_comment`. Discriminated enum (serde adjacent
 * `kind`/`data` tags) so the TS side can branch cleanly. Every per-comment
 * mutation flows through this enum so the IPC surface stays a single
 * chokepoint.
 */
export type CommentPatch = 
/**
 * Append a reaction. Idempotent on (`user`, `kind`) — adding the same
 * reaction twice from the same user is a no-op so renderer-side
 * double-clicks don't pollute the sidecar.
 */
{ kind: "add_reaction"; data: { user: string; kind: string; ts: string } } | 
/**
 * Toggle resolved state. Canonical resolve/unresolve path — the
 * legacy `set_comment_resolved` IPC command was removed in iter 2 to
 * keep `update_comment` as the single per-comment mutation entry.
 */
{ kind: "set_resolved"; data: { resolved: boolean } } | 
/**
 * Replace the canonical `anchor` and push the prior value through the
 * `push_anchor_history` chokepoint (FIFO-clamped at 3). Equal-anchor
 * applies are a no-op so re-anchoring with the same value doesn't
 * pollute history or fire `comments-changed`. Reuses the tagged
 * `AnchorRepr` wire format via `{ new_anchor: Anchor }`.
 */
{ kind: "move_anchor"; data: { new_anchor: AnchorWire } }
/**
 * A thread: root comment with replies sorted by timestamp.
 */
export type CommentThread = { root: MatchedComment; replies: MatchedComment[] }
/**
 * Discriminated error: each variant carries a stable `kind` tag the TS side
 * can branch on (mirrors `system::SystemError`).
 */
export type ConfigError = 
/**
 * Author rejected by validation (length / control chars / newlines).
 * `reason` is a short machine-readable token, not free-form prose.
 */
{ kind: "InvalidAuthor"; reason: string } | 
/**
 * Persisting onboarding state failed (disk full, permission denied, etc.).
 */
{ kind: "IoError"; message: string }
export type CsvCellAnchor = { row_idx: number; col_idx: number; col_header: string; primary_key_col?: string | null; primary_key_value?: string | null }
export type DefaultHandlerStatus = "done" | "other" | "unknown" | "unsupported"
export type DirEntry = { name: string; path: string; is_dir: boolean }
/**
 * Per-file badge: count of unresolved threads + max severity across them.
 * `file_level_count` is the subset of `count` whose root anchor is
 * `Anchor::File` — surfaced separately so the viewer toolbar can show a
 * dedicated file-anchored thread badge.
 */
export type FileBadge = { count: number; max_severity: Severity; file_level_count: number }
/**
 * Lightweight `stat`: returns just the byte size of a file, with no content
 * read. Used by viewers (BinaryPlaceholder, TooLargePlaceholder) that need
 * to display a size without paying the I/O cost of `read_binary_file`. No
 * 10 MB cap — over-cap files are exactly the case we want to surface.
 * 
 * Workspace-allowlisted: mirrors `commands/system.rs::reveal_in_folder` so a
 * malicious renderer cannot probe arbitrary paths (e.g. `~/.ssh/id_rsa`)
 * for existence/size. The path must be inside an open workspace folder or
 * an open tab.
 */
export type FileStat = { size_bytes: number; 
/**
 * Last-modified time as epoch milliseconds. `None` if the platform/FS
 * does not expose mtime or it is before the UNIX epoch. Field name
 * mirrors the MRSF `*_ms` epoch convention.
 */
mtime_ms: number | null }
/**
 * The public-facing pref returned over IPC (no internal bookkeeping fields).
 */
export type FileViewerPref = { allow_images: boolean }
export type FoldRegion = { 
/**
 * 1-based line number where the foldable region starts.
 */
startLine: number; 
/**
 * 1-based, inclusive line number where the foldable region ends.
 */
endLine: number }
/**
 * Result of [`get_file_comments`]: matched/grouped threads plus the mtime
 * of the sidecar file the loader actually picked. `sidecar_mtime_ms` is
 * `None` when no sidecar exists for `file_path` (or the platform/FS does
 * not expose mtime). Callers can use the value to detect external sidecar
 * edits without a follow-up IPC. Field name mirrors the `*_ms` epoch
 * convention used by [`crate::commands::FileStat::mtime_ms`].
 */
export type GetFileCommentsResult = { threads: CommentThread[]; sidecar_mtime_ms: number | null }
export type HtmlElementAnchor = { selector_path: string; tag: string; text_preview: string }
export type HtmlRangeAnchor = { selector_path: string; start_offset: number; end_offset: number; selected_text: string }
export type ImageRectAnchor = { x_pct: number; y_pct: number; w_pct?: number | null; h_pct?: number | null }
export type JsonPathAnchor = { json_path: string; scalar_text?: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KqlPipelineStep = { step: number; operator: string; details: string; isSource: boolean }
export type LaunchArgs = { files: string[]; folders: string[] }
export type MatchedComment = ({ id: string; author: string; timestamp: string; text: string; resolved: boolean; line?: number | null; end_line?: number | null; start_column?: number | null; end_column?: number | null; selected_text?: string | null; anchored_text?: string | null; selected_text_hash?: string | null; commit?: string | null; type?: string | null; severity?: string | null; reply_to?: string | null; anchor_kind?: string | null; image_rect?: ImageRectAnchor | null; csv_cell?: CsvCellAnchor | null; json_path?: JsonPathAnchor | null; html_range?: HtmlRangeAnchor | null; html_element?: HtmlElementAnchor | null; word_range?: WordRangePayload | null; anchor_history?: AnchorWire[] | null; reactions?: Reaction[] | null }) & { matchedLineNumber: number; isOrphaned: boolean; anchoredText?: string | null }
/**
 * Direction to migrate sidecars.
 */
export type MigrateDirection = 
/**
 * Move co-located sidecars into the `sidecar_root` folder.
 */
"to_folder" | 
/**
 * Move folder sidecars back to co-located positions.
 */
"to_colocated"
export type MigrateSidecarsResult = { moved: number; failed: string[]; config: SidecarConfigResult }
/**
 * Wire-format anchor for `add_comment`. Accepts BOTH the legacy flat
 * `{ line, ... }` shape used by line-anchored composers and the tagged
 * `{ kind: "...", ... }` shape introduced for file-level + typed
 * anchors (Group A/B). Untagged so the JS chokepoint (`addComment` in
 * `lib/tauri-commands.ts`) does not have to convert.
 */
export type NewCommentAnchor = TaggedNewAnchor | CommentAnchor
export type OnboardingState = { schema_version: number; last_seen_sections?: string[]; 
/**
 * Display name written into `MrsfComment.author` for new comments.
 * Set via `commands::config::set_author`. Persisted alongside other
 * onboarding bits because it's a one-off, settings-shaped value with no
 * natural home elsewhere.
 */
author?: string | null }
/**
 * Outcome of a `check_path_exists` probe. Serialized as a bare lowercase
 * string ("file" / "dir" / "missing") so the wire shape matches the prior
 * hand-mirrored TS literal union — but the enum forces specta to emit the
 * union in `bindings.ts` so the façade can drop its `as` cast and a future
 * variant addition fails the codegen drift gate.
 */
export type PathKind = "file" | "dir" | "missing"
export type Reaction = { user: string; kind: string; ts: string }
/**
 * Capped directory listing: entries + total count + overflow flag.
 */
export type ReadDirResult = { entries: DirEntry[]; total: number; has_more: boolean }
export type SearchMatch = { lineIndex: number; startCol: number; endCol: number }
/**
 * Total order of severity for badge selection. `None` is the absence of any
 * severity tag — comments with no severity sort below `Low`.
 */
export type Severity = "none" | "low" | "medium" | "high"
export type SidecarConfigResult = { enabled: boolean; sidecar_root: string | null; count_in_folder: number; count_colocated: number }
/**
 * Typed error surfaced to the renderer. Discriminated with an internal `kind`
 * tag so the TS side can branch on it without parsing prose strings.
 */
export type SystemError = 
/**
 * Caller asked us to act on a path outside the open workspace and not in
 * any open tab. This is the only path-validation outcome the renderer
 * can recover from (e.g. by surfacing an "open the folder first" prompt).
 */
{ kind: "PathOutsideWorkspace" } | 
/**
 * The OS-level spawn failed (binary missing, permission denied, etc.).
 */
{ kind: "IoError"; message: string } | 
/**
 * The current platform has no implementation (e.g. Linux `xdg-open`
 * missing in a barebones container).
 */
{ kind: "Unsupported" }
/**
 * Tagged variant of [`NewCommentAnchor`]. Mirrors the TS `Anchor` union
 * in `src/lib/anchor-derive.ts` — discriminator is `kind`, payload fields
 * are flattened alongside it (internally tagged).
 */
export type TaggedNewAnchor = { kind: "line"; line: number; end_line?: number | null; start_column?: number | null; end_column?: number | null; selected_text?: string | null; selected_text_hash?: string | null } | { kind: "file" } | ({ kind: "word_range" } & WordRangePayload)
/**
 * Result of [`read_text_file`]: file content plus cheap-to-compute metadata
 * (byte size and line count) that the UI surfaces in the status bar without
 * requiring a second IPC round-trip.
 */
export type TextFileResult = { content: string; size_bytes: number; line_count: number; 
/**
 * Last-modified time as epoch milliseconds. `None` if the platform/FS
 * does not expose mtime or it is before the UNIX epoch. Mirrors the
 * `*_ms` epoch convention used by [`FileStat::mtime_ms`]. Surfaced
 * here so callers can detect external edits (mtime jumps) without a
 * follow-up `stat_file` IPC round-trip.
 */
mtime_ms: number | null }
export type UpdateInfo = { version: string; body: string | null }
/**
 * v1.1 word-range anchor payload (Group D-wire, iter 3). Targets a contiguous
 * run of UAX #29 word tokens on a single line. `start_word` / `end_word` are
 * 0-based indices into the line's word stream produced by
 * [`crate::core::word_tokens::tokenize_words`]; `snippet` is a small
 * human-readable preview and `line_text_hash` is the lowercase-hex sha256 of
 * the anchored line at capture time (used by the resolver to detect drift).
 * 
 * Hardening lives in [`WordRangePayload::sanitize`], called at the wire→domain
 * conversion boundary so attackers can't smuggle bidi confusables, oversize
 * blobs, NUL bytes, or non-hex hashes into in-memory anchors.
 */
export type WordRangePayload = { start_word: number; end_word: number; line: number; snippet: string; line_text_hash: string }
/**
 * One word-like segment produced by [`tokenize_words`]. Byte offsets are
 * indexes into the original UTF-8 input — the renderer can map back to
 * rendered glyphs trivially.
 */
export type WordSpan = { start: number; end: number; text: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
