/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by tauri-specta. DO NOT EDIT.
// Source: src-tauri/src/lib.rs::build_specta_builder.
// Regenerate (Linux/macOS): `cd src-tauri && cargo test --features codegen --test specta_codegen generate_bindings_ts`.
// Regenerate (Windows):     `cd src-tauri && MDOWNREVIEW_GEN_BINDINGS_ONLY=1 cargo run --features codegen`.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Read directory entries, rejecting path traversal.
 * Returns at most `limit` entries (default 250) with total count so the
 * frontend can offer a "Show all N items…" affordance.
 * Hides `.review.yaml`/`.review.json` sidecar files, and also hides the
 * `sidecar_root` directory when listing a workspace root with an active
 * redirect (AC10: prevents users from seeing the internal sidecar store).
 */
async readDir(path: string, limit: number | null, showSidecars: boolean | null) : Promise<Result<ReadDirResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_dir", { path, limit, showSidecars }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a text file, rejecting binary files and files >10 MB. Returns
 * decoded UTF-8 + `size_bytes` + `line_count` + `mtime_ms`. Workspace-
 * allowlisted via [`ensure_readable`]; cap + TOCTOU semantics live in
 * [`read_file_capped`] (see also `docs/security.md` rules 1-3).
 */
async readTextFile(path: string) : Promise<Result<TextFileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_text_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a binary file, returning base64-encoded content. Rejects files
 * >10 MB. Workspace-allowlisted via [`ensure_readable`]; cap semantics
 * live in [`read_file_capped`].
 */
async readBinaryFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_binary_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async statFile(path: string) : Promise<Result<FileStat, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stat_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the OS file manager and select the file at `path`.
 * 
 * Workspace-allowlisted via `WatcherState::is_path_allowed`. On Linux there
 * is no portable "select" — we open the parent directory instead.
 */
async revealInFolder(path: string) : Promise<Result<null, SystemError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Inline local images as data URIs and stylesheets as `<style>` blocks.
 * Replaces the previous TS implementation in `src/lib/resolve-html-assets.ts`.
 * Per-asset failures preserve the original tag (graceful fallback).
 */
async resolveHtmlAssets(html: string, htmlDir: string) : Promise<string> {
    return await TAURI_INVOKE("resolve_html_assets", { html, htmlDir });
},
/**
 * Get (and drain) launch args queued for the calling window.
 */
async getLaunchArgs() : Promise<Result<LaunchArgs, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_launch_args") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the log file path for display in the About dialog.
 */
async getLogPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan a directory tree for MRSF sidecar files (delegates to core::scanner).
 * 
 * Honours the workspace's `.mrsf.yaml` redirect so sidecars stored
 * under e.g. `.reviews/` are mapped back to their real source location
 * instead of being incorrectly flagged as ghosts. Both the GUI IPC
 * and the CLI go through [`crate::core::scanner::scan_workspace`] for
 * identical `(sidecar, source)` output.
 */
async scanReviewFiles(root: string) : Promise<Result<([string, string])[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_review_files", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if a path exists and whether it is a directory or file.
 */
async checkPathExists(path: string) : Promise<PathKind> {
    return await TAURI_INVOKE("check_path_exists", { path });
},
/**
 * Canonicalize an absolute path to the long form without the Windows `\\?\`
 * verbatim prefix. Used by the renderer to normalize paths at workspace-open
 * and tab-open boundaries so that string-equality comparisons against
 * scanner output (which itself canonicalizes via `dunce`) match. No
 * workspace guard — this is the very command callers use to obtain the
 * canonical form before they have a workspace to validate against.
 */
async canonicalizePath(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("canonicalize_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a UTF-8 text payload to a workspace file (Excalidraw scene JSON or
 * `.excalidrawlib`). Bounds: parent inside workspace, extension in
 * allowlist, no `:` in filename, byte length ≤ `WORKSPACE_WRITE_MAX_BYTES`,
 * atomic write.
 */
async writeWorkspaceText(path: string, text: string) : Promise<Result<null, WorkspaceWriteError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_workspace_text", { path, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a binary payload (base64-encoded on the wire) to a workspace file
 * (`.excalidraw.png` / `.excalidraw.svg` re-rendered with embedded scene).
 */
async writeWorkspaceBinary(path: string, base64: string) : Promise<Result<null, WorkspaceWriteError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_workspace_binary", { path, base64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renderer-side ack for a close-flush request. Idempotent: a second call
 * (or a call before the request was registered) is a no-op.
 */
async closeFlushComplete(label: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_flush_complete", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renderer marks itself ready to handle `flush-before-close` requests.
 * Called once from the `useExcalidrawCloseFlush` mount effect. Until
 * this fires, the close handler skips the prevent_close round-trip
 * to avoid the 2.5 s timeout lag for cold-start closes.
 */
async markCloseFlushReady() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_close_flush_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renderer-side `openFile` action awaits this before adding a tab.
 * Returns `Claimed` for unowned paths or same-window re-claims.
 * Returns `OwnedElsewhere` when another live window owns the path,
 * in which case Rust ALSO focuses the owner window and emits
 * `focus-tab` to it — the renderer just needs to bail.
 */
async claimOpenFile(path: string) : Promise<Result<ClaimResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("claim_open_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Renderer fires this from `closeTab` / single-tab eviction. Only
 * the owner releases. Idempotent — non-owners and missing entries
 * are no-ops. If the file has been deleted between tab-close and
 * the IPC, canonicalisation fails; we still attempt a path-string
 * match against stored keys, and the destroy-window sweep is the
 * final safety net.
 */
async releaseOpenFile(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("release_open_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bulk release for `closeAllTabs` / multi-tab eviction. Same
 * semantics as `release_open_file` per path.
 */
async releaseOpenFiles(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("release_open_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Combined hot-path: load sidecar → match to file lines → build threads.
 * Single IPC call for the GUI's most common operation.
 * 
 * Comments are partitioned by anchor variant: `Line`/`File` go through the
 * existing `match_comments` batch algorithm (line-targeting heuristics);
 * typed anchors (CSV cell, JSON path, HTML range/element, image rect,
 * word range) are dispatched through [`crate::core::anchors::resolve_anchor`]
 * against a single shared [`crate::core::anchors::LazyParsedDoc`] so the
 * file is parsed at most once per call (lazily, only for the
 * representations the present anchors actually need).
 * 
 * Workspace-allowlisted via [`enforce_workspace_path`] (advisory #5 / iter-4
 * security blocker S2): rejects paths the user has not opened so a renderer
 * cannot probe arbitrary files. The file body itself is read with a 10 MB
 * cap (matching `read_text_file` and `SIDECAR_MAX_BYTES`) — anything larger
 * degrades silently to empty bytes so all comments orphan, identical to the
 * `NotFound` branch.
 */
async getFileComments(filePath: string) : Promise<Result<GetFileCommentsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_comments", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new comment, save to sidecar.
 * 
 * `clippy::too_many_arguments` is intentionally permitted here: this is a
 * `#[tauri::command]`, so its parameter list is the IPC wire shape consumed
 * by `invoke("add_comment", { ... })` on the JS side. Grouping arguments
 * into a struct would change the wire contract.
 */
async addComment(filePath: string, author: string, text: string, anchor: NewCommentAnchor | null, commentType: string | null, severity: string | null, document: string | null) : Promise<Result<null, CommentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_comment", { filePath, author, text, anchor, commentType, severity, document }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a reply to an existing comment, save to sidecar.
 */
async addReply(filePath: string, parentId: string, author: string, text: string) : Promise<Result<null, CommentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_reply", { filePath, parentId, author, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a comment's text, save to sidecar.
 */
async editComment(filePath: string, commentId: string, text: string) : Promise<Result<null, CommentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_comment", { filePath, commentId, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a comment (with reply reparenting per MRSF §9.1), save to sidecar.
 */
async deleteComment(filePath: string, commentId: string) : Promise<Result<null, CommentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_comment", { filePath, commentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compute SHA-256 hash for selected text anchor.
 */
async computeAnchorHash(text: string) : Promise<string> {
    return await TAURI_INVOKE("compute_anchor_hash", { text });
},
/**
 * Apply a [`CommentPatch`] to a single comment.
 */
async updateComment(filePath: string, commentId: string, patch: CommentPatch) : Promise<Result<null, CommentError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_comment", { filePath, commentId, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-file unresolved-thread count + worst severity.
 */
async getFileBadges(filePaths: string[]) : Promise<Result<Partial<{ [key in string]: FileBadge }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_badges", { filePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAuthor(name: string) : Promise<Result<string, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_author", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAuthor() : Promise<Result<string, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_author") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTheme(theme: string) : Promise<Result<null, ConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchInDocument(content: string, query: string) : Promise<SearchMatch[]> {
    return await TAURI_INVOKE("search_in_document", { content, query });
},
async computeFoldRegions(content: string, language: string) : Promise<FoldRegion[]> {
    return await TAURI_INVOKE("compute_fold_regions", { content, language });
},
async parseKql(query: string) : Promise<KqlPipelineStep[]> {
    return await TAURI_INVOKE("parse_kql", { query });
},
async stripJsonComments(text: string) : Promise<string> {
    return await TAURI_INVOKE("strip_json_comments", { text });
},
async onboardingState() : Promise<Result<OnboardingState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("onboarding_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cliShimStatus() : Promise<CliShimStatus> {
    return await TAURI_INVOKE("cli_shim_status");
},
async installCliShim() : Promise<Result<null, CliShimError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_cli_shim") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCliShim() : Promise<Result<null, CliShimError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_cli_shim") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async defaultHandlerStatus() : Promise<DefaultHandlerStatus> {
    return await TAURI_INVOKE("default_handler_status");
},
async setDefaultHandler() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_handler") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileViewerPref(path: string) : Promise<FileViewerPref | null> {
    return await TAURI_INVOKE("get_file_viewer_pref", { path });
},
async setFileViewerPref(path: string, allowImages: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_file_viewer_pref", { path, allowImages }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: update the set of watched file paths.
 * The frontend calls this whenever the set of open tabs changes.
 */
async updateWatchedFiles(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_watched_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the set of directories whose direct children should produce
 * `folder-changed` events (root + currently-expanded folders in the tree pane).
 * 
 * `root` and every entry in `dirs` are canonicalized internally; callers may
 * pass any absolute form. Each entry must exist and be a directory, and every
 * dir must be contained within `root`. At most
 * [`crate::watcher::MAX_TREE_WATCHED_DIRS`] entries per call.
 * 
 * Also loads the `.mrsf.yaml` config for the workspace root and caches
 * its `sidecar_root` value in [`SidecarConfigState`] so that subsequent
 * sidecar reads/writes use the configured path.
 */
async updateTreeWatchedDirs(root: string, dirs: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_tree_watched_dirs", { root, dirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async tokenizeWords(text: string) : Promise<Result<WordSpan[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tokenize_words", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Classify `href` (optionally resolved against `base_dir`) for the workspace
 * associated with the calling window.
 */
async pathClassify(href: string, baseDir: string | null) : Promise<Result<PathClassification, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("path_classify", { href, baseDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSidecarConfig(root: string) : Promise<Result<SidecarConfigResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sidecar_config", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSidecarConfig(root: string, enabled: boolean) : Promise<Result<SidecarConfigResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sidecar_config", { root, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async migrateSidecarsCmd(root: string, direction: MigrateDirection) : Promise<Result<MigrateSidecarsResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("migrate_sidecars_cmd", { root, direction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a startup phase from the frontend. Mirrors
 * `StartupPhase` 1:1 — see that enum for the kebab-case wire shape
 * (`"theme-applied"`, `"frontend-mounted"`, `"first-file-loaded"`).
 */
async recordStartupPhase(phase: StartupPhase) : Promise<void> {
    await TAURI_INVOKE("record_startup_phase", { phase });
},
/**
 * Check for an update on the given channel.
 * For cross-channel switches the version comparator is overridden
 * to accept any different version (enabling "downgrades").
 */
async checkUpdate(channel: string) : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_update", { channel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and install the pending update. Emits "update-progress"
 * events so the frontend can show a progress bar.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerWindowFolder(folder: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_window_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterWindowFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_window_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a user-initiated file open with the per-window scope.
 * 
 * Called by the renderer's tab-open chokepoint BEFORE dispatching
 * `read_text_file` so that `ensure_readable`'s `is_path_allowed` check
 * passes. Adds the file's canonical-parent to the per-window
 * `tree_watched_dirs` allowlist (watcher-seed only — does NOT widen
 * asset-scope; that's the banner opt-in via `extend_window_scope_files`).
 * 
 * Security:
 * - Canonicalises the input via `canonicalize_no_verbatim` (rejects `..`,
 * relative, verbatim).
 * - Classifies the canonical path via
 * `core::security::system_locations::classify` and rejects `Tier::System`
 * with the sentinel "system path blocked" matching
 * `commands::fs::mod::ensure_readable`'s vocabulary.
 * - Returns the canonical path plus a `PathClassification` so the renderer
 * can derive `readOnly` atomically with the tab insert (AC7 — eliminates
 * the `classifyAndMarkReadOnly` race).
 * 
 * Cite: docs/architecture.md rule 1 (chokepoint discipline) +
 * docs/security.md rule 17 (asset-scope vs watcher-allowlist split).
 */
async registerWindowFile(path: string) : Promise<Result<RegisterWindowFileResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_window_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Extend per-window scope (BOTH asset-protocol scope AND watcher allowlist)
 * for the given paths' canonical parents. Used by:
 * 1. The "Allow for this session" banner click in the markdown viewer
 * (AC3) — grants asset scope to embedded image directories.
 * 2. Future single-window deferred grants. Idempotent.
 * 
 * Each path is canonicalized and classified. `Tier::System` paths are
 * rejected with the "system path blocked" sentinel; non-canonical paths
 * with "path not canonicalizable". On any per-path rejection, the IPC
 * returns Err and no partial mutation occurs (atomic — collect all
 * canonicals first, then call `extend_window_scope` once).
 * 
 * Cite: docs/security.md rule 17 (asset-scope chokepoint, banner opt-in).
 */
async extendWindowScopeFiles(paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extend_window_scope_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test-only command: open a folder and all its non-sidecar files via args-received.
 */
async setRootViaTest(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_root_via_test", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test-only IPC clearing all per-window scope state for the calling
 * window. Used by `e2e/native/fixtures.ts`'s `nativePage` fixture so
 * each spec starts with an empty `tree_watched_dirs` precondition,
 * closing the cross-spec state-leak surface that produced #366.
 * 
 * `#[cfg(debug_assertions)]`-gated — release builds do not register
 * this command at all. Mirrors `set_root_via_test` (line 153-224).
 * 
 * Cite: docs/security.md rule 20 (debug-only IPC gate).
 */
async resetWindowScopeForTest() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_window_scope_for_test") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Specta-shadow for [`AnchorRepr`]. Mirrors the wire JSON shape
 * (`{anchor_kind, anchor_data}`) emitted by the hand-rolled serde
 * impls below. Used only for TS codegen; never (de)serialised at
 * runtime. Iter 2 may sharpen `anchor_data` into a discriminated
 * union for better TS ergonomics.
 * 
 * Referenced exclusively via field-level `#[specta(type = AnchorWire)]`
 * forwarding on every public struct that names `Anchor` or
 * `AnchorRepr` (see `Anchor` in `mod.rs` and `MrsfCommentRepr`'s
 * `anchor_history` field). `AnchorRepr` itself does NOT derive
 * `specta::Type` because the hand-rolled `Serialize` / `Deserialize`
 * impls below produce a shape that the natural enum-derive cannot
 * describe accurately.
 */
export type AnchorWire = { anchor_kind: string; anchor_data: JsonValue }
/**
 * Wire-shape for the claim result. Kebab-case discriminator, same
 * pattern as `WorkspaceWriteError` in `commands/fs_write.rs`.
 */
export type ClaimResult = 
/**
 * Caller now owns the path (or already did — idempotent).
 */
{ kind: "claimed" } | 
/**
 * Another live window owns the path. Renderer should NOT add a
 * tab; the Rust handler has already raised the owner window and
 * emitted `focus-tab` to it. The label is exposed so the
 * renderer can log / surface diagnostics; callers don't need it
 * for the main flow.
 */
{ kind: "owned-elsewhere"; window_label: string }
/**
 * Structured error for CLI-shim install/remove. Serializes to a tagged
 * payload (`{"kind":"...", ...}`) so the FE can branch on `kind` without
 * string matching. Manual `Display` impl avoids pulling in `thiserror`.
 */
export type CliShimError = { kind: "permission_denied"; path: string; target: string } | { kind: "io"; message: string }
export type CliShimStatus = "done" | "missing" | "broken" | "unsupported"
/**
 * Anchor specification for creating new comments.
 */
export type CommentAnchor = { line: number; end_line?: number | null; start_column?: number | null; end_column?: number | null; selected_text?: string | null; selected_text_hash?: string | null }
/**
 * Tagged error returned by comment-mutation IPCs. Discriminated with an
 * internal `kind` tag (kebab-case on the wire) so the TS side can branch
 * on `err.kind` without parsing prose.
 */
export type CommentError = 
/**
 * Canonical path outside the per-window workspace allowlist.
 * AC3 of #338: the renderer surfaces this as a tab-level "read-only"
 * indicator. The path is included so the consumer can self-heal the
 * corresponding tab without a separate IPC round-trip.
 */
{ kind: "outside-workspace"; path: string } | 
/**
 * Canonical path matches the system-locations DENY list.
 * AC11 of #338: tier-3 hard-block, no allow-toggle.
 */
{ kind: "system-blocked" } | 
/**
 * I/O or sidecar-shape failure. Catch-all for now; future iters may
 * split this further. Carries the original error text so the renderer
 * can surface it verbatim in a toast (matches the pre-#338 string
 * surface — no information lost).
 */
{ kind: "io"; message: string }
/**
 * Patch payloads for `update_comment`. Discriminated enum (serde adjacent
 * `kind`/`data` tags) so the TS side can branch cleanly. Every per-comment
 * mutation flows through this enum so the IPC surface stays a single
 * chokepoint.
 */
export type CommentPatch = 
/**
 * Append a reaction. Idempotent on (`user`, `kind`) — adding the same
 * reaction twice from the same user is a no-op so renderer-side
 * double-clicks don't pollute the sidecar.
 */
{ kind: "add_reaction"; data: { user: string; kind: string; ts: string } } | 
/**
 * Toggle resolved state. Canonical resolve/unresolve path — the
 * legacy `set_comment_resolved` IPC command was removed in iter 2 to
 * keep `update_comment` as the single per-comment mutation entry.
 */
{ kind: "set_resolved"; data: { resolved: boolean } }
/**
 * A thread: root comment with replies sorted by timestamp.
 */
export type CommentThread = { root: MatchedComment; replies: MatchedComment[] }
/**
 * Discriminated error: each variant carries a stable `kind` tag the TS side
 * can branch on (mirrors `system::SystemError`).
 */
export type ConfigError = 
/**
 * Author rejected by validation (length / control chars / newlines).
 * `reason` is a short machine-readable token, not free-form prose.
 */
{ kind: "InvalidAuthor"; reason: string } | 
/**
 * Theme rejected by validation. Renderer never sends garbage but this is
 * defense-in-depth. Closed enum (no `reason` field) — the only valid values
 * are "system" / "light" / "dark" so a single tag is sufficient.
 */
{ kind: "InvalidTheme" } | 
/**
 * Persisting onboarding state failed (disk full, permission denied, etc.).
 */
{ kind: "IoError"; message: string }
export type CsvCellAnchor = { row_idx: number; col_idx: number; col_header: string; primary_key_col?: string | null; primary_key_value?: string | null }
export type DefaultHandlerStatus = "done" | "other" | "unknown" | "unsupported"
export type DirEntry = { name: string; path: string; is_dir: boolean }
/**
 * Per-file badge: count of unresolved threads + max severity across them.
 * `file_level_count` is the subset of `count` whose root anchor is
 * `Anchor::File` — surfaced separately so the viewer toolbar can show a
 * dedicated file-anchored thread badge.
 */
export type FileBadge = { count: number; max_severity: Severity; file_level_count: number }
/**
 * Lightweight `stat`: returns just the byte size of a file, with no content
 * read. Used by viewers (BinaryPlaceholder, TooLargePlaceholder) that need
 * to display a size without paying the I/O cost of `read_binary_file`. No
 * 10 MB cap — over-cap files are exactly the case we want to surface.
 * 
 * Workspace-allowlisted: mirrors `commands/system.rs::reveal_in_folder` so a
 * malicious renderer cannot probe arbitrary paths (e.g. `~/.ssh/id_rsa`)
 * for existence/size. The path must be inside an open workspace folder or
 * an open tab.
 */
export type FileStat = { size_bytes: number; 
/**
 * Last-modified time as epoch milliseconds. `None` if the platform/FS
 * does not expose mtime or it is before the UNIX epoch. Field name
 * mirrors the MRSF `*_ms` epoch convention.
 */
mtime_ms: number | null }
/**
 * The public-facing pref returned over IPC (no internal bookkeeping fields).
 */
export type FileViewerPref = { allow_images: boolean }
export type FoldRegion = { 
/**
 * 1-based line number where the foldable region starts.
 */
startLine: number; 
/**
 * 1-based, inclusive line number where the foldable region ends.
 */
endLine: number }
/**
 * Result of [`get_file_comments`]: matched/grouped threads plus the mtime
 * of the sidecar file the loader actually picked. `sidecar_mtime_ms` is
 * `None` when no sidecar exists for `file_path` (or the platform/FS does
 * not expose mtime). Callers can use the value to detect external sidecar
 * edits without a follow-up IPC. Field name mirrors the `*_ms` epoch
 * convention used by [`crate::commands::FileStat::mtime_ms`].
 */
export type GetFileCommentsResult = { threads: CommentThread[]; sidecar_mtime_ms: number | null }
export type HtmlElementAnchor = { selector_path: string; tag: string; text_preview: string }
export type HtmlRangeAnchor = { selector_path: string; start_offset: number; end_offset: number; selected_text: string }
export type ImageRectAnchor = { x_pct: number; y_pct: number; w_pct?: number | null; h_pct?: number | null }
export type JsonPathAnchor = { json_path: string; scalar_text?: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KqlPipelineStep = { step: number; operator: string; details: string; isSource: boolean }
export type LaunchArgs = { files: string[]; folders: string[] }
export type MatchedComment = ({ id: string; author: string; timestamp: string; text: string; resolved: boolean; line?: number | null; end_line?: number | null; start_column?: number | null; end_column?: number | null; selected_text?: string | null; anchored_text?: string | null; selected_text_hash?: string | null; commit?: string | null; type?: string | null; severity?: string | null; reply_to?: string | null; anchor_kind?: string | null; image_rect?: ImageRectAnchor | null; csv_cell?: CsvCellAnchor | null; json_path?: JsonPathAnchor | null; html_range?: HtmlRangeAnchor | null; html_element?: HtmlElementAnchor | null; word_range?: WordRangePayload | null; anchor_history?: AnchorWire[] | null; reactions?: Reaction[] | null }) & { matchedLineNumber: number; isOrphaned: boolean; anchoredText?: string | null; 
/**
 * The line value verbatim from `MrsfComment.line` BEFORE the matcher
 * rewrote `comment.line` during re-anchoring. `None` for
 * legacy file-level comments, `Anchor::File`, `Anchor::Unknown`, and
 * `Anchor::WordRange` paths that bypass `match_comments`. Used by the
 * UI to surface "originally line X → re-anchored to Y" without a
 * silent reanchor (issue #280 AC5).
 */
originalLine?: number | null }
/**
 * Direction to migrate sidecars.
 */
export type MigrateDirection = 
/**
 * Move co-located sidecars into the `sidecar_root` folder.
 */
"to_folder" | 
/**
 * Move folder sidecars back to co-located positions.
 */
"to_colocated"
export type MigrateSidecarsResult = { moved: number; failed: string[]; config: SidecarConfigResult }
/**
 * Wire-format anchor for `add_comment`. Accepts BOTH the legacy flat
 * `{ line, ... }` shape used by line-anchored composers and the tagged
 * `{ kind: "...", ... }` shape introduced for file-level + typed
 * anchors (Group A/B). Untagged so the JS chokepoint (`addComment` in
 * `lib/tauri-commands.ts`) does not have to convert.
 */
export type NewCommentAnchor = TaggedNewAnchor | CommentAnchor
export type OnboardingState = { schema_version: number; last_seen_sections?: string[]; 
/**
 * Display name written into `MrsfComment.author` for new comments.
 * Set via `commands::config::set_author`. Persisted alongside other
 * onboarding bits because it's a one-off, settings-shaped value with no
 * natural home elsewhere.
 */
author?: string | null; 
/**
 * User's theme preference. One of `"system"`, `"light"`, or `"dark"`.
 * Read at window-construction time by `commands::config::resolve_window_bg`
 * to set `WebviewWindowBuilder::background_color` BEFORE WebView2 attaches —
 * fixes the cold-start light-theme flash regression from PR #265. Set via
 * `commands::config::set_theme` IPC. Persisted in this struct (rather than
 * a dedicated settings file) for the same reason as `author`: one-off
 * settings knob, no value in splitting the file. Schema version stays at 1
 * because this is an additive optional field — backward-compat with old
 * binaries that drop unknown keys.
 */
theme?: string | null }
export type PathClassification = { tier: "inside"; canonical: string } | { tier: "outside"; canonical: string } | { tier: "system"; flavor: PathClassificationFlavor }
export type PathClassificationFlavor = "posix" | "windows" | "unc"
/**
 * Outcome of a `check_path_exists` probe. Serialized as a bare lowercase
 * string ("file" / "dir" / "missing") so the wire shape matches the prior
 * hand-mirrored TS literal union — but the enum forces specta to emit the
 * union in `bindings.ts` so the façade can drop its `as` cast and a future
 * variant addition fails the codegen drift gate.
 */
export type PathKind = "file" | "dir" | "missing"
export type Reaction = { user: string; kind: string; ts: string }
/**
 * Capped directory listing: entries + total count + overflow flag.
 */
export type ReadDirResult = { entries: DirEntry[]; total: number; has_more: boolean }
export type RegisterWindowFileResult = { canonical: string; classification: PathClassification }
export type SearchMatch = { lineIndex: number; startCol: number; endCol: number }
/**
 * Total order of severity for badge selection. `None` is the absence of any
 * severity tag — comments with no severity sort below `Low`.
 */
export type Severity = "none" | "low" | "medium" | "high"
export type SidecarConfigResult = { enabled: boolean; sidecar_root: string | null; count_in_folder: number; count_colocated: number }
/**
 * Ordered phases of app startup, mirrored to TypeScript via specta as a
 * kebab-case string union (`"app-init" | "webview-ready" | ...`). Each
 * phase is recorded at most once per process lifetime.
 * 
 * Order of expected emission:
 * 1. `AppInit` — Rust `pub fn run` first instruction.
 * 2. `WebviewReady` — main webview's `Created` window event.
 * 3. `FirstIpc` — first call through any `#[mdr_command]` IPC.
 * 4. `ThemeApplied` — frontend reports after applying initial theme
 * (PR4 will move this to a pre-React script tag).
 * 5. `FrontendMounted` — React's `App` finished its first effect.
 * 6. `FirstFileLoaded` — the user's first viewer paint completes.
 * 
 * Phase order is not enforced — async timing differences mean the recorder
 * must accept events in any sequence.
 */
export type StartupPhase = "app-init" | "webview-ready" | "first-ipc" | "theme-applied" | "frontend-mounted" | "first-file-loaded"
/**
 * Typed error surfaced to the renderer. Discriminated with an internal `kind`
 * tag so the TS side can branch on it without parsing prose strings.
 */
export type SystemError = 
/**
 * Caller asked us to act on a path outside the open workspace and not in
 * any open tab. This is the only path-validation outcome the renderer
 * can recover from (e.g. by surfacing an "open the folder first" prompt).
 */
{ kind: "PathOutsideWorkspace" } | 
/**
 * The OS-level spawn failed (binary missing, permission denied, etc.).
 */
{ kind: "IoError"; message: string } | 
/**
 * The current platform has no implementation (e.g. Linux `xdg-open`
 * missing in a barebones container).
 */
{ kind: "Unsupported" }
/**
 * Tagged variant of [`NewCommentAnchor`]. Mirrors the TS `Anchor` union
 * in `src/lib/anchor-derive.ts` — discriminator is `kind`, payload fields
 * are flattened alongside it (internally tagged).
 */
export type TaggedNewAnchor = { kind: "line"; line: number; end_line?: number | null; start_column?: number | null; end_column?: number | null; selected_text?: string | null; selected_text_hash?: string | null } | { kind: "file" } | ({ kind: "word_range" } & WordRangePayload)
/**
 * Result of [`read_text_file`]: file content plus cheap-to-compute metadata
 * (byte size and line count) that the UI surfaces in the status bar without
 * requiring a second IPC round-trip.
 */
export type TextFileResult = { content: string; size_bytes: number; line_count: number; 
/**
 * Last-modified time as epoch milliseconds. `None` if the platform/FS
 * does not expose mtime or it is before the UNIX epoch. Mirrors the
 * `*_ms` epoch convention used by [`super::FileStat::mtime_ms`]. Surfaced
 * here so callers can detect external edits (mtime jumps) without a
 * follow-up `stat_file` IPC round-trip.
 */
mtime_ms: number | null }
export type UpdateInfo = { version: string; body: string | null }
/**
 * v1.1 word-range anchor payload (Group D-wire, iter 3). Targets a contiguous
 * run of UAX #29 word tokens on a single line. `start_word` / `end_word` are
 * 0-based indices into the line's word stream produced by
 * [`crate::core::word_tokens::tokenize_words`]; `snippet` is a small
 * human-readable preview and `line_text_hash` is the lowercase-hex sha256 of
 * the anchored line at capture time (used by the resolver to detect drift).
 * 
 * Hardening lives in [`WordRangePayload::sanitize`], called at the wire→domain
 * conversion boundary so attackers can't smuggle bidi confusables, oversize
 * blobs, NUL bytes, or non-hex hashes into in-memory anchors.
 */
export type WordRangePayload = { start_word: number; end_word: number; line: number; snippet: string; line_text_hash: string }
/**
 * One word-like segment produced by [`tokenize_words`]. Byte offsets are
 * indexes into the original UTF-8 input — the renderer can map back to
 * rendered glyphs trivially.
 */
export type WordSpan = { start: number; end: number; text: string }
/**
 * Issue #352 / iter-12 (architect HIGH#3 + security MEDIUM#3) — typed
 * workspace-write error.
 * 
 * The previous `Result<(), String>` return surface forced the renderer
 * to substring-match the Rust prose in `friendlySaveError` — a wire
 * contract maintained by string sniffing that silently breaks if the
 * Rust message format ever changes (rule `architecture-rust-first` in
 * `docs/architecture.md`). The typed enum is round-tripped via
 * tauri-specta so the renderer branches on `err.kind` directly. See
 * `src/lib/excalidraw/error-mapping.ts` for the consumer.
 * 
 * Discriminator is `kind`, kebab-case on the wire — same shape as
 * `CommentError` (see `commands/comments/error.rs`).
 */
export type WorkspaceWriteError = 
/**
 * Canonical path is outside any open workspace folder, OR target
 * is an existing symlink whose target escapes the workspace.
 */
{ kind: "outside-workspace"; path: string } | 
/**
 * Lowercased filename suffix is not in `WORKSPACE_WRITE_ALLOWLIST`.
 * Carries the offending filename so a renderer can hint at the
 * correct extension family.
 */
{ kind: "ext-not-allowed"; filename: string } | 
/**
 * Filename contains a forbidden character (currently only `:`,
 * the NTFS Alternate Data Stream marker).
 */
{ kind: "filename-invalid"; reason: string } | 
/**
 * Decoded payload exceeds `WORKSPACE_WRITE_MAX_BYTES`. Surfaces
 * the observed byte count so the renderer can compute an MB
 * figure for user-facing copy.
 */
{ kind: "payload-too-large"; observed_bytes: number } | 
/**
 * Base64 string was structurally invalid (only emitted by the
 * binary IPC).
 */
{ kind: "invalid-base-64"; detail: string } | 
/**
 * I/O failure during canonicalisation, atomic-rename, or any
 * underlying syscall. Fallback variant carrying the original error
 * text so a renderer can surface a developer-debuggable string.
 */
{ kind: "io"; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
