//! Integration tests for `mdownreview-cli analyze-log` (issue #265 / PR4).
//!
//! Mirrors `cli_integration.rs`'s pattern: spawn the built binary,
//! capture stdout/stderr/exit, assert. Fixtures live under
//! `tests/fixtures/logs/` so they can be regenerated by hand if the
//! schema ever evolves.
//!
//! The pure-function branch (parser, percentile, budget evaluator) is
//! covered by `#[cfg(test)] mod tests` in
//! `src-tauri/src/cli/analyze_log.rs` so this file focuses on the
//! BINARY surface — flag parsing, file I/O, exit codes.

use std::path::PathBuf;
use std::process::Command;

fn cli_binary() -> PathBuf {
    // CARGO_TARGET_TMPDIR points to target/tmp; the binary lives in target/debug.
    let mut path = PathBuf::from(env!("CARGO_TARGET_TMPDIR"));
    path.pop();
    path.push("debug");
    path.push(if cfg!(windows) {
        "mdownreview-cli.exe"
    } else {
        "mdownreview-cli"
    });
    path
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("logs")
}

fn run_cli(args: &[&str]) -> (String, String, i32) {
    let output = Command::new(cli_binary())
        .args(args)
        .output()
        .expect("failed to execute CLI binary");
    (
        String::from_utf8_lossy(&output.stdout).to_string(),
        String::from_utf8_lossy(&output.stderr).to_string(),
        output.status.code().unwrap_or(-1),
    )
}

// ── well-formed ────────────────────────────────────────────────────────────

#[test]
fn well_formed_text_output_lists_all_phases_and_commands() {
    let log = fixtures_dir().join("well_formed.log");
    let (stdout, _stderr, code) = run_cli(&["analyze-log", log.to_str().unwrap()]);
    assert_eq!(code, 0, "stdout was: {stdout}");
    // Every phase from the fixture appears exactly once.
    for phase in &[
        "app-init",
        "webview-ready",
        "first-ipc",
        "theme-applied",
        "frontend-mounted",
        "first-file-loaded",
    ] {
        assert!(stdout.contains(phase), "missing phase {phase} in:\n{stdout}");
    }
    // Every command name from the fixture appears in the IPC table.
    for cmd in &[
        "read_text_file",
        "read_dir",
        "stat_file",
        "get_file_comments",
        "record_startup_phase",
    ] {
        assert!(stdout.contains(cmd), "missing cmd {cmd} in:\n{stdout}");
    }
    // Header is the canonical text shape.
    assert!(stdout.contains("Startup phase timeline"));
    assert!(stdout.contains("IPC commands"));
}

#[test]
fn well_formed_json_output_has_documented_schema() {
    let log = fixtures_dir().join("well_formed.log");
    let (stdout, _stderr, code) = run_cli(&["analyze-log", log.to_str().unwrap(), "--json"]);
    assert_eq!(code, 0, "stdout was: {stdout}");
    let parsed: serde_json::Value = serde_json::from_str(&stdout).expect("valid JSON");
    assert_eq!(parsed["schema_version"], 1);

    let phases = parsed["startup_phases"].as_array().expect("array");
    assert_eq!(phases.len(), 6);
    // Sorted ascending by t_ms.
    assert_eq!(phases[0]["phase"], "app-init");
    assert_eq!(phases[0]["t_ms"], 0);
    assert_eq!(phases[1]["phase"], "theme-applied");
    assert_eq!(phases[1]["t_ms"], 12);

    let cmds = parsed["ipc_commands"].as_array().expect("array");
    assert_eq!(cmds.len(), 5);
    // First entry has highest total_us (sorted desc).
    let first = &cmds[0];
    assert!(first["total_us"].as_u64().unwrap() > 0);
    // Every entry carries the documented field set.
    for c in cmds {
        for field in &["name", "count", "p50_us", "p95_us", "p99_us", "total_us"] {
            assert!(c.get(field).is_some(), "missing field {field} in {c}");
        }
    }
}

#[test]
fn well_formed_percentiles_match_fixture() {
    let log = fixtures_dir().join("well_formed.log");
    let (stdout, _stderr, code) = run_cli(&["analyze-log", log.to_str().unwrap(), "--json"]);
    assert_eq!(code, 0);
    let parsed: serde_json::Value = serde_json::from_str(&stdout).unwrap();
    let cmds = parsed["ipc_commands"].as_array().unwrap();
    let read_text_file = cmds
        .iter()
        .find(|c| c["name"] == "read_text_file")
        .expect("read_text_file present");
    // Fixture has 10 read_text_file durations sorted: 950, 1050, 1100,
    // 1200, 1250, 1300, 1500, 2400, 3100, 8100. p50 nearest-rank index
    // = ceil(0.5*10)-1 = 4 → 1250. p95 = ceil(0.95*10)-1 = 9 → 8100.
    assert_eq!(read_text_file["count"], 10);
    assert_eq!(read_text_file["p50_us"], 1250);
    assert_eq!(read_text_file["p95_us"], 8100);
    assert_eq!(read_text_file["p99_us"], 8100);
}

// ── malformed ──────────────────────────────────────────────────────────────

#[test]
fn malformed_log_skips_garbage_silently() {
    let log = fixtures_dir().join("malformed.log");
    let (stdout, _stderr, code) = run_cli(&["analyze-log", log.to_str().unwrap()]);
    assert_eq!(code, 0, "expected 0; got {code}, stdout was:\n{stdout}");
    // Only the well-formed lines should round-trip through.
    assert!(stdout.contains("app-init"));
    assert!(stdout.contains("frontend-mounted"));
    assert!(stdout.contains("read_text_file"));
    assert!(stdout.contains("ok"));
    // The garbage `t_ms=NOT_A_NUMBER` line should NOT produce a phase
    // labelled `webview-ready` — verify by absence in the output.
    assert!(
        !stdout.contains("webview-ready"),
        "malformed t_ms accepted: {stdout}"
    );
}

// ── empty ──────────────────────────────────────────────────────────────────

#[test]
fn empty_log_produces_clean_output_and_passes_budgets_vacuously() {
    let log = fixtures_dir().join("empty.log");
    let (stdout, _stderr, code) = run_cli(&[
        "analyze-log",
        log.to_str().unwrap(),
        "--phase-budget",
        "frontend-mounted=10",
    ]);
    assert_eq!(code, 0, "expected 0; got {code}");
    assert!(stdout.contains("(no [startup] events found)"));
    assert!(stdout.contains("(no [ipc] events found)"));
}

// ── truncated ──────────────────────────────────────────────────────────────

#[test]
fn truncated_log_does_not_panic() {
    let log = fixtures_dir().join("truncated.log");
    let (stdout, _stderr, code) = run_cli(&["analyze-log", log.to_str().unwrap()]);
    assert_eq!(code, 0, "stdout was: {stdout}");
    assert!(stdout.contains("app-init"));
    // Final partial line is silently dropped.
    assert!(stdout.contains("read_text_file"));
}

// ── --phase-budget ─────────────────────────────────────────────────────────

#[test]
fn phase_budget_breach_exits_nonzero_with_message() {
    let log = fixtures_dir().join("well_formed.log");
    // frontend-mounted in fixture is t_ms=387; budget=10 → breach.
    let (_stdout, stderr, code) = run_cli(&[
        "analyze-log",
        log.to_str().unwrap(),
        "--phase-budget",
        "frontend-mounted=10",
    ]);
    assert_eq!(code, 2, "stderr was: {stderr}");
    assert!(stderr.contains("BUDGET BREACH"));
    assert!(stderr.contains("frontend-mounted"));
    assert!(stderr.contains("387"));
}

#[test]
fn phase_budget_within_limit_passes() {
    let log = fixtures_dir().join("well_formed.log");
    // Generous budget — 387 < 5000.
    let (_stdout, _stderr, code) = run_cli(&[
        "analyze-log",
        log.to_str().unwrap(),
        "--phase-budget",
        "frontend-mounted=5000",
    ]);
    assert_eq!(code, 0);
}

#[test]
fn phase_budget_multiple_breaches_all_reported() {
    let log = fixtures_dir().join("well_formed.log");
    let (_stdout, stderr, code) = run_cli(&[
        "analyze-log",
        log.to_str().unwrap(),
        "--phase-budget",
        "frontend-mounted=10",
        "--phase-budget",
        "first-file-loaded=10",
    ]);
    assert_eq!(code, 2);
    let breach_lines: Vec<&str> = stderr
        .lines()
        .filter(|l| l.contains("BUDGET BREACH"))
        .collect();
    assert_eq!(breach_lines.len(), 2, "stderr: {stderr}");
}

#[test]
fn phase_budget_invalid_format_rejected() {
    let log = fixtures_dir().join("empty.log");
    let (_stdout, stderr, code) = run_cli(&[
        "analyze-log",
        log.to_str().unwrap(),
        "--phase-budget",
        "no-equals-sign",
    ]);
    assert_eq!(code, 2);
    assert!(stderr.contains("invalid --phase-budget"));
}

// ── --stdin ────────────────────────────────────────────────────────────────

#[test]
fn stdin_reads_from_pipe() {
    use std::io::Write;
    use std::process::Stdio;

    let mut child = Command::new(cli_binary())
        .args(["analyze-log", "--stdin", "--json"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn analyze-log");
    let log = b"[startup] phase=app-init t_ms=0\n[ipc] cmd=foo duration_us=10 payload_bytes=0 ok=true\n";
    child
        .stdin
        .as_mut()
        .unwrap()
        .write_all(log)
        .expect("write stdin");
    let output = child.wait_with_output().expect("wait");
    assert_eq!(output.status.code().unwrap_or(-1), 0);
    let parsed: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("valid JSON");
    assert_eq!(parsed["startup_phases"][0]["phase"], "app-init");
    assert_eq!(parsed["ipc_commands"][0]["name"], "foo");
}

// ── stdin + path are mutually exclusive ────────────────────────────────────

#[test]
fn stdin_and_path_are_mutually_exclusive() {
    let log = fixtures_dir().join("empty.log");
    let (_stdout, stderr, code) =
        run_cli(&["analyze-log", "--stdin", log.to_str().unwrap()]);
    // clap usage error → exit 2.
    assert_eq!(code, 2);
    assert!(
        stderr.contains("cannot be used") || stderr.contains("conflicts"),
        "stderr: {stderr}"
    );
}

// ── nonexistent path ────────────────────────────────────────────────────────

#[test]
fn nonexistent_path_reports_error() {
    let (_stdout, stderr, code) =
        run_cli(&["analyze-log", "definitely/does/not/exist.log"]);
    assert_eq!(code, 1);
    assert!(stderr.contains("error"));
}

// ── help discoverability ───────────────────────────────────────────────────

#[test]
fn analyze_log_appears_in_top_level_help() {
    let (stdout, _stderr, code) = run_cli(&["--help"]);
    assert_eq!(code, 0);
    assert!(
        stdout.contains("analyze-log"),
        "missing analyze-log in --help: {stdout}"
    );
    assert!(stdout.contains("--phase-budget"));
}
