//! Bindings.ts regeneration test (issue #263).
//!
//! Calls `mdown_review_lib::build_specta_builder().export(...)` to
//! produce `../src/lib/bindings.ts`. This is the deterministic
//! regeneration hook for CI; iter 3 will gate PRs on the file being
//! up-to-date. The test asserts the file exists, is non-trivial,
//! and carries the AUTO-GENERATED header so `eslint-disable` covers
//! the whole file.
//!
//! Why a separate file from `specta_coverage.rs`? Referencing
//! `mdown_review_lib::build_specta_builder` pulls `tauri::Wry`,
//! `tauri-runtime-wry`, and the WebView2 import table into the test
//! binary. On some Windows dev hosts (incl. the iteration-development
//! host) the linked binary fails to start with
//! `STATUS_ENTRYPOINT_NOT_FOUND` (0xC0000139). Splitting the syn-walk
//! meta-test out into `specta_coverage.rs` (which has zero
//! `mdown_review_lib::*` references) keeps THAT test fast and
//! platform-portable. The codegen test stays `#[ignore]`'d on Windows
//! and is exercised on macOS / Linux CI runners (where webview2 isn't
//! a factor) and on Windows runners with a recent WebView2 runtime.
//!
//! For Windows-only local regeneration: run `cargo build` (which
//! launches the lib's `run()` in debug mode and exports bindings.ts
//! via the `#[cfg(debug_assertions)]` block). When in doubt,
//! `cargo test --test specta_codegen -- --ignored` will force-run on
//! Windows; if your host has webview2, the test passes.

// On Windows, the entire body is `#[cfg(not(target_os = "windows"))]`-gated
// (NOT just `#[ignore]`'d at the test attribute). Test attributes only fire
// AFTER the binary has loaded successfully, but the whole point of skipping
// on Windows is that linking against `mdown_review_lib::build_specta_builder`
// pulls webview2 imports that may fail at LoadLibrary time on dev hosts.
// A windows-stub test exists below so `cargo test --test specta_codegen`
// reports a meaningful skip message rather than 0 tests.

#[cfg(not(target_os = "windows"))]
mod codegen {
    use std::path::Path;

    #[test]
    fn generate_bindings_ts() {
        let builder = mdown_review_lib::build_specta_builder();
        let header = "/* eslint-disable */\n// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n// Source: src-tauri/src/lib.rs::build_specta_builder. Regenerate with `cd src-tauri && cargo test --test specta_codegen generate_bindings_ts`.\n\n";
        let out_path = "../src/lib/bindings.ts";
        builder
            .export(
                specta_typescript::Typescript::default().header(header),
                out_path,
            )
            .expect("export bindings.ts");

        // `out_path` is relative to the manifest dir; resolve it for the assertions.
        let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
        let abs = manifest_dir.join(out_path);
        let bytes =
            std::fs::read(&abs).unwrap_or_else(|e| panic!("read {}: {e}", abs.display()));
        assert!(
            bytes.len() > 100,
            "bindings.ts is suspiciously small ({} bytes) — codegen likely wrong",
            bytes.len()
        );
        let s = String::from_utf8_lossy(&bytes);
        assert!(
            s.contains("/* eslint-disable */"),
            "bindings.ts is missing the eslint-disable header"
        );
        assert!(
            s.contains("AUTO-GENERATED"),
            "bindings.ts is missing the AUTO-GENERATED marker"
        );
    }
}

#[cfg(target_os = "windows")]
mod codegen {
    /// Stub on Windows so the test target still has at least one item
    /// to link. `mdown_review_lib::build_specta_builder` pulls webview2
    /// imports that may fail at LoadLibrary time on Windows dev hosts;
    /// see the file-level doc comment for the full rationale.
    #[test]
    #[ignore = "tauri::Wry pulls webview2 import table that fails to load on \
                some Windows dev hosts (STATUS_ENTRYPOINT_NOT_FOUND, 0xC0000139). \
                The production build's `cargo build` still re-emits bindings.ts \
                via `lib.rs::run`'s `#[cfg(debug_assertions)]` block. CI on \
                macOS / Linux / Windows-with-WebView2 still runs this test."]
    fn generate_bindings_ts() {
        // Intentionally empty: the runtime never reaches here because
        // the test is `#[ignore]`'d AND the body must not link
        // `mdown_review_lib::build_specta_builder` on Windows.
    }
}
