// Self-alias so the `#[mdr_command]` proc-macro (in `mdr-macros/`) can
// emit absolute paths like `::mdown_review_lib::startup_recorder::…`
// uniformly — both INSIDE this crate's compile units AND in downstream
// integration tests. Without this, a bare `::mdown_review_lib::…` path
// inside `lib.rs` itself fails E0433 because the crate cannot
// self-reference by name. This is the canonical Rust pattern for
// proc-macros that need an absolute path back to the host crate.
extern crate self as mdown_review_lib;

pub mod commands;
pub mod core;
pub mod instance_scope;
pub mod log_rotation;
pub mod macros;
pub mod registry;
pub mod startup_recorder;
pub mod tracing_log_bridge;
pub mod update;
pub mod watcher;

// Re-export `#[mdr_command]` at the crate root so call sites read
// `use crate::mdr_command;` (or `use mdown_review_lib::mdr_command;`
// from tests) instead of the deeper `crate::macros::mdr_command`.
// See `macros/mod.rs` for the indirection rationale.
pub use macros::mdr_command;

use commands::{parse_launch_args, LaunchArgs};
#[cfg(all(debug_assertions, feature = "codegen"))]
use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri::menu::{Menu, MenuBuilder, MenuItem, SubmenuBuilder};
use tauri::{Emitter, Manager, Runtime};
use tauri_plugin_log::{Target, TargetKind};

// ---------------------------------------------------------------------------
// Single source of truth for the bindings.ts header literal. Both the
// runtime export path (this file's `run()` debug block) and the test export
// path (`tests/specta_codegen.rs::generate_bindings_ts`) reference this
// constant so the two cannot drift. iter-3's drift gate compares the file
// produced by EACH path against the committed `src/lib/bindings.ts`; if the
// headers diverged, every PR after one of the two ran would show a diff.
// ---------------------------------------------------------------------------

/// Header prepended to `src/lib/bindings.ts`. Kept in lockstep with both
/// the runtime export (in `run()` below) and the codegen test.
pub const BINDINGS_HEADER: &str = "/* eslint-disable */\n// @ts-nocheck\n// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n// Source: src-tauri/src/lib.rs::build_specta_builder.\n// Regenerate (Linux/macOS): `cd src-tauri && cargo test --features codegen --test specta_codegen generate_bindings_ts`.\n// Regenerate (Windows):     `cd src-tauri && MDOWNREVIEW_GEN_BINDINGS_ONLY=1 cargo run --features codegen`.\n\n";

// ---------------------------------------------------------------------------
// Multi-window helpers
// ---------------------------------------------------------------------------

/// Raise and focus a window (un-minimize → show → set-focus).
fn focus_window(win: &tauri::WebviewWindow) {
    let _ = win.unminimize();
    let _ = win.show();
    let _ = win.set_focus();
}

/// Extract a human-readable name from a path (last component, or full path).
fn folder_display_name(path: &std::path::Path) -> String {
    path.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| path.to_string_lossy().into_owned())
}

// ---------------------------------------------------------------------------
// Per-window menu: encode window label into each menu item ID so
// on_menu_event can route to the correct originating window.
// See rule `multiwin-per-window-menu` in docs/best-practices-common/tauri/v2-patterns.md.
// ---------------------------------------------------------------------------

/// Encode a menu item ID as `{window_label}:{action}`.
fn encode_menu_id(label: &str, action: &str) -> String {
    format!("{label}:{action}")
}

/// Parse a menu item ID back into `(window_label, action)`.
/// Returns `None` for un-prefixed global IDs (e.g. "new-window").
fn parse_menu_id(id: &str) -> Option<(&str, &str)> {
    id.split_once(':')
}

/// Build the application menu for a specific window. Each menu item ID is
/// prefixed with the window label so `on_menu_event` can identify the
/// originating window without heuristics.
fn build_window_menu<R: Runtime, M: Manager<R>>(
    handle: &M,
    label: &str,
) -> tauri::Result<Menu<R>> {
    let id = |action: &str| encode_menu_id(label, action);

    let open_file =
        MenuItem::with_id(handle, id("open-file"), "Open File…", true, Some("CmdOrCtrl+O"))?;
    let open_folder = MenuItem::with_id(
        handle, id("open-folder"), "Open Folder…", true, Some("CmdOrCtrl+Shift+O"),
    )?;
    let close_folder =
        MenuItem::with_id(handle, id("close-folder"), "Close Folder", true, None::<&str>)?;
    let new_window = MenuItem::with_id(
        handle, id("new-window"), "New Window", true, None::<&str>,
    )?;
    let close_tab =
        MenuItem::with_id(handle, id("close-tab"), "Close Tab", true, Some("CmdOrCtrl+W"))?;
    let close_all_tabs = MenuItem::with_id(
        handle, id("close-all-tabs"), "Close All Tabs", true, Some("CmdOrCtrl+Shift+W"),
    )?;
    let help_settings = MenuItem::with_id(handle, id("help-settings"), "Settings…", true, Some("CmdOrCtrl+,"))?;
    let file_menu = SubmenuBuilder::new(handle, "File")
        .item(&new_window)
        .separator()
        .item(&open_file)
        .item(&open_folder)
        .item(&close_folder)
        .separator()
        .item(&close_tab)
        .item(&close_all_tabs)
        .separator()
        .item(&help_settings)
        .separator()
        .quit()
        .build()?;

    let toggle_comments_pane = MenuItem::with_id(
        handle, id("toggle-comments-pane"), "Toggle Comments Pane", true, Some("CmdOrCtrl+Shift+C"),
    )?;
    let next_tab = MenuItem::with_id(handle, id("next-tab"), "Next Tab", true, None::<&str>)?;
    let prev_tab = MenuItem::with_id(handle, id("prev-tab"), "Previous Tab", true, None::<&str>)?;
    let theme_system = MenuItem::with_id(handle, id("theme-system"), "System Theme", true, None::<&str>)?;
    let theme_light = MenuItem::with_id(handle, id("theme-light"), "Light Theme", true, None::<&str>)?;
    let theme_dark = MenuItem::with_id(handle, id("theme-dark"), "Dark Theme", true, None::<&str>)?;
    let theme_menu = SubmenuBuilder::new(handle, "Theme")
        .item(&theme_system).item(&theme_light).item(&theme_dark).build()?;
    let view_menu = SubmenuBuilder::new(handle, "View")
        .item(&toggle_comments_pane).separator()
        .item(&next_tab).item(&prev_tab).separator()
        .item(&theme_menu).build()?;

    let win_minimize = MenuItem::with_id(handle, id("win-minimize"), "Minimize", true, None::<&str>)?;
    let win_bring_all = MenuItem::with_id(handle, id("win-bring-all"), "Bring All to Front", true, None::<&str>)?;
    // Developer Tools — available in BOTH debug and release builds. Enabled by
    // the `devtools` Cargo feature on the `tauri` crate (see Cargo.toml). F12
    // is the universal cross-platform accelerator (also accepted natively by
    // WebView2/WKWebView in dev builds, so users get muscle-memory parity in
    // production via this menu item). Rust-handled in `on_menu_event` like the
    // other window-frame actions (`win-minimize`, `win-bring-all`).
    let toggle_devtools = MenuItem::with_id(
        handle, id("toggle-devtools"), "Toggle Developer Tools", true, Some("F12"),
    )?;
    let window_menu = SubmenuBuilder::new(handle, "Window")
        .item(&win_minimize).separator().item(&win_bring_all)
        .separator().item(&toggle_devtools).build()?;

    let about_item = MenuItem::with_id(handle, id("about"), "About mdownreview", true, None::<&str>)?;
    let check_updates = MenuItem::with_id(handle, id("check-updates"), "Check for Updates…", true, None::<&str>)?;
    let help_menu = SubmenuBuilder::new(handle, "Help")
        .item(&check_updates).separator().item(&about_item).build()?;

    MenuBuilder::new(handle)
        .item(&file_menu).item(&view_menu).item(&window_menu).item(&help_menu)
        .build()
}

/// Create a new application window with its own per-window menu.
fn create_app_window(
    handle: &tauri::AppHandle,
    label: &str,
    title: &str,
) -> tauri::Result<tauri::WebviewWindow> {
    let menu = build_window_menu(handle, label)?;
    tauri::WebviewWindowBuilder::new(handle, label, tauri::WebviewUrl::App("index.html".into()))
        .title(title)
        .inner_size(1100.0, 750.0)
        .min_inner_size(600.0, 400.0)
        .menu(menu)
        .build()
}

/// Shared logic for opening a new empty window. Used by the native menu handler.
fn open_new_window(app: &tauri::AppHandle) -> Result<(), String> {
    let reg = app.state::<registry::WindowRegistry>();
    let new_label = reg.next_label();
    create_app_window(app, &new_label, "mdownreview")
        .map(|_| {
            reg.register(new_label.clone(), registry::WindowKind::FileOnly);
            log::info!("[window] new-window: created {new_label}");
        })
        .map_err(|e| format!("failed to create window: {e}"))
}

#[mdr_command]
fn register_window_folder(
    window: tauri::Window,
    folder: String,
    registry: tauri::State<'_, registry::WindowRegistry>,
) -> Result<(), String> {
    let canonical = crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(&folder))
        .map_err(|e| format!("invalid folder: {}", e))?;
    let display = folder_display_name(&canonical);
    match registry.try_claim_folder(window.label(), canonical.clone()) {
        Ok(()) => {
            let _ = window.set_title(&format!("mdownreview — {display}"));
            log::info!("[window] {} registered folder: {display}", window.label());
            Ok(())
        }
        Err(existing_label) => {
            // Focus the window that already owns this folder
            if let Some(existing_win) = window.app_handle().get_webview_window(&existing_label) {
                focus_window(&existing_win);
            }
            log::info!(
                "[window] {} tried to claim folder {display} already owned by {existing_label}",
                window.label()
            );
            Err(format!("folder already open in window '{existing_label}'"))
        }
    }
}

#[mdr_command]
fn unregister_window_folder(
    window: tauri::Window,
    registry: tauri::State<'_, registry::WindowRegistry>,
) -> Result<(), String> {
    registry.update_kind(window.label(), registry::WindowKind::FileOnly);
    let _ = window.set_title("mdownreview");
    log::info!("[window] {} unregistered folder", window.label());
    Ok(())
}

/// Route incoming `LaunchArgs` through the `WindowRegistry`, creating new
/// windows for unknown folders and focusing existing ones.  Shared by the
/// single-instance callback, `setup()`, and `RunEvent::Opened`.
fn route_args_through_registry(
    handle: &tauri::AppHandle,
    args: &LaunchArgs,
    ctx: &str,
) {
    let Some(reg) = handle.try_state::<registry::WindowRegistry>() else {
        return;
    };
    for folder in &args.folders {
        let canonical = crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(folder))
            .unwrap_or_else(|_| std::path::PathBuf::from(folder));
        match reg.route_folder(&canonical) {
            registry::RouteDecision::FocusExisting(label) => {
                if let Some(win) = handle.get_webview_window(&label) {
                    focus_window(&win);
                }
            }
            registry::RouteDecision::CreateFolder { path } => {
                let label = reg.next_label();
                let display = folder_display_name(&path);
                match create_app_window(handle, &label, &format!("mdownreview — {display}")) {
                    Ok(new_win) => {
                        reg.register(label.clone(), registry::WindowKind::Folder(path.clone()));
                        reg.push_args(&label, LaunchArgs {
                            folders: vec![path.to_string_lossy().into_owned()],
                            files: vec![],
                        });
                        // Rule multiwin-args-delivery: signal the new window to re-drain
                        // in case its initial mount drain fired before push_args.
                        let _ = new_win.emit("args-received", ());
                        log::info!("[window] {ctx}: created {label}");
                    }
                    Err(e) => log::error!("[window] {ctx}: folder window failed: {e}"),
                }
            }
            _ => {}
        }
    }
    for file in &args.files {
        let canonical = crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(file))
            .unwrap_or_else(|_| std::path::PathBuf::from(file));
        match reg.route_file(&canonical) {
            registry::RouteDecision::AddToWindow { label, files } => {
                if let Some(win) = handle.get_webview_window(&label) {
                    focus_window(&win);
                    let _ = win.emit("open-file-tab", &files);
                }
            }
            registry::RouteDecision::CreateFileOnly { files } => {
                let label = reg.next_label();
                match create_app_window(handle, &label, "mdownreview — Files") {
                    Ok(new_win) => {
                        reg.register(label.clone(), registry::WindowKind::FileOnly);
                        let file_strs: Vec<String> = files.iter().map(|f| f.to_string_lossy().into_owned()).collect();
                        reg.push_args(&label, LaunchArgs { files: file_strs, folders: vec![] });
                        // Rule multiwin-args-delivery: signal the new window to re-drain.
                        let _ = new_win.emit("args-received", ());
                        log::info!("[window] {ctx}: created file-only window {label}");
                    }
                    Err(e) => log::error!("[window] {ctx}: file-only window failed: {e}"),
                }
            }
            registry::RouteDecision::FocusExisting(label) => {
                if let Some(win) = handle.get_webview_window(&label) {
                    focus_window(&win);
                }
            }
            _ => {}
        }
    }
}

/// Build the `tauri_specta::Builder` carrying every IPC command.
///
/// The 41-command stable list is declared exactly ONCE inside the
/// `specta_commands!` `macro_rules!` below. Debug builds append
/// `set_root_via_test` (used only by the native e2e harness); release
/// builds get the empty extras list. The textual list never appears
/// twice in the source, satisfying the Never-Increase-Debt principle
/// (`docs/principles.md`) and rule 23 file-size budget in
/// `docs/architecture.md`.
///
/// The returned builder owns the command registry; its `.invoke_handler()`
/// REPLACES the previous `tauri::generate_handler![]` call. In debug
/// builds with `--features codegen`, [`pub fn run`] also calls `.export()`
/// on this builder to emit `src/lib/bindings.ts` (issue #263).
///
/// `commands::remote_asset::fetch_remote_asset` is NOT registered here —
/// it returns a `tauri::ipc::Response` (binary IPC) that specta cannot
/// describe. It is registered separately via the merge pattern below.
/// Iter 2 may revisit.
pub fn build_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    // The inner `tauri_specta::collect_commands!` is a `macro_rules!`
    // taking a comma-separated list of paths (with optional turbofish
    // generics). We splat `$($extra:tt)*` raw into the tail; an empty
    // splat just leaves the trailing comma after `unregister_window_folder`,
    // which `collect_commands!`'s `$(,)?` accepts.
    macro_rules! specta_commands {
        ($($extra:tt)*) => {
            tauri_specta::collect_commands![
                commands::fs::read_dir,
                commands::fs::read_text_file,
                commands::fs::read_binary_file,
                commands::fs::stat_file,
                commands::system::reveal_in_folder,
                commands::html::resolve_html_assets,
                commands::launch::get_launch_args,
                commands::launch::get_log_path,
                commands::launch::scan_review_files,
                commands::fs::check_path_exists,
                commands::fs::canonicalize_path,
                commands::comments::get::get_file_comments,
                commands::comments::add_comment::<tauri::Wry>,
                commands::comments::add_reply::<tauri::Wry>,
                commands::comments::edit_comment::<tauri::Wry>,
                commands::comments::delete_comment::<tauri::Wry>,
                commands::comments::compute_anchor_hash,
                commands::comments::update::update_comment::<tauri::Wry>,
                commands::comments::badges::get_file_badges,
                commands::config::set_author,
                commands::config::get_author,
                commands::search::search_in_document,
                commands::html::compute_fold_regions,
                commands::search::parse_kql,
                commands::search::strip_json_comments,
                commands::onboarding::onboarding_state,
                commands::cli_shim::cli_shim_status,
                commands::cli_shim::install_cli_shim,
                commands::cli_shim::remove_cli_shim,
                commands::default_handler::default_handler_status,
                commands::default_handler::set_default_handler,
                commands::file_viewer_prefs::get_file_viewer_pref,
                commands::file_viewer_prefs::set_file_viewer_pref,
                watcher::update_watched_files,
                commands::fs::update_tree_watched_dirs,
                commands::word_tokens::tokenize_words,
                commands::sidecar_config::get_sidecar_config,
                commands::sidecar_config::set_sidecar_config,
                commands::sidecar_config::migrate_sidecars_cmd,
                commands::startup::record_startup_phase,
                update::check_update,
                update::install_update,
                register_window_folder,
                unregister_window_folder,
                $($extra)*
            ]
        };
    }

    #[cfg(debug_assertions)]
    {
        tauri_specta::Builder::<tauri::Wry>::new()
            .commands(specta_commands![commands::launch::set_root_via_test])
    }
    #[cfg(not(debug_assertions))]
    {
        tauri_specta::Builder::<tauri::Wry>::new().commands(specta_commands![])
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Anchor the StartupRecorder timeline. Touching `record_phase` here
    // also forces lazy `OnceLock` init so the `t_ms` baseline matches
    // the user-visible "process start" rather than the first IPC call.
    // See `startup_recorder` for the schema (`[startup] phase=app-init t_ms=…`).
    startup_recorder::record_phase(startup_recorder::StartupPhase::AppInit);

    // Apply the IPC trace gate precedence chain BEFORE the Tauri builder
    // spins up the runtime (no IPC dispatches before `Builder::build()`
    // returns, so the gate is set before any `#[mdr_command]` call reads
    // it via `ipc_trace_enabled()`):
    //
    //   1. `--trace[=on|off]` launch flag  (highest)
    //   2. `MDR_IPC_TRACE` env var         (existing escape hatch)
    //   3. `cfg!(debug_assertions)`        (debug-on by default)
    //
    // See `docs/observability.md` for the user-facing description and
    // `commands::launch::parse_trace_flag` for accepted flag forms.
    let early_argv: Vec<String> = std::env::args().skip(1).collect();
    let trace_enabled = commands::launch::parse_trace_flag(&early_argv)
        .or_else(|| std::env::var("MDR_IPC_TRACE").ok().map(|_| true))
        .unwrap_or(cfg!(debug_assertions));
    startup_recorder::set_ipc_trace_enabled(trace_enabled);

    let log_plugin = {
        let mut builder = tauri_plugin_log::Builder::new()
            .max_file_size(5 * 1024 * 1024)
            .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepAll);

        #[cfg(debug_assertions)]
        {
            builder = builder.level(log::LevelFilter::Debug).targets([
                Target::new(TargetKind::Webview),
                Target::new(TargetKind::LogDir {
                    file_name: Some("mdownreview".to_string()),
                }),
                Target::new(TargetKind::Stdout),
            ]);
        }
        #[cfg(not(debug_assertions))]
        {
            builder = builder.level(log::LevelFilter::Info).targets([
                Target::new(TargetKind::Webview)
                    .filter(|metadata| metadata.level() <= log::Level::Warn),
                Target::new(TargetKind::LogDir {
                    file_name: Some("mdownreview".to_string()),
                }),
            ]);
        }

        builder.build()
    };

    // Install tracing → log bridge so the existing `tracing::*` call sites
    // throughout `commands/`, `core/`, and `watcher.rs` reach
    // `tauri-plugin-log` (without this, every structured `tracing::warn!`
    // is silently dropped — see `tracing_log_bridge` rustdoc for the
    // history). Must run BEFORE the first `tracing::*` call site fires; the
    // tauri builder below uses some `tracing::*` calls indirectly so we
    // install it as early as possible after building the log plugin.
    tracing_log_bridge::install();

    let (sync_tx, sync_rx) = std::sync::mpsc::sync_channel::<()>(1);

    let mut builder = tauri::Builder::default()
        // The log-rotator MUST be registered before tauri-plugin-log:
        // its setup hook archives the previous `mdownreview.log` (if any)
        // and prunes the directory to log_rotation::DEFAULT_KEEP files,
        // all before the log plugin opens the file for append. Plugin
        // setup hooks fire in registration order — same contract that
        // tauri-plugin-single-instance relies on. See
        // `src-tauri/src/log_rotation.rs` for details.
        .plugin(log_rotation::plugin())
        .plugin(log_plugin)
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_clipboard_manager::init());

    // Production builds enforce single-instance; debug/test-isolated builds
    // skip it so multiple instances can coexist (AC 7 of #147).
    if !instance_scope::is_isolated() {
        builder = builder.plugin(tauri_plugin_single_instance::init(
            |app, argv, cwd| {
                let cwd_path = std::path::PathBuf::from(&cwd);
                let args = parse_launch_args(&argv[1..], &cwd_path);

                route_args_through_registry(app, &args, "single-instance");
            },
        ));
    }

    let app = builder
        .plugin(tauri_plugin_updater::Builder::new().build())
        .manage(update::PendingUpdate(std::sync::Mutex::new(None)))
        .manage(watcher::WatcherState::new(sync_tx))
        .manage(watcher::SidecarConfigState::new())
        .manage(watcher::SyncRx(std::sync::Mutex::new(Some(sync_rx))))
        .manage(registry::WindowRegistry::default())
        .manage(commands::comments::BadgeCache::new())
        .setup(|app| {
            // Register panic hook to log panics before process terminates
            let prev_hook = std::panic::take_hook();
            std::panic::set_hook(Box::new(move |info| {
                let msg = info.payload().downcast_ref::<&str>().copied()
                    .or_else(|| info.payload().downcast_ref::<String>().map(|s| s.as_str()))
                    .unwrap_or("unknown panic");
                let loc = info.location()
                    .map(|l| format!(" at {}:{}", l.file(), l.line()))
                    .unwrap_or_default();
                log::error!("[rust] PANIC{loc}: {msg}");
                prev_hook(info);
            }));

            // Surface the log-rotator's outcome as a structured
            // `[startup]` line. The rotator runs BEFORE tauri-plugin-log
            // is up so it cannot use `log::info!` itself (the call
            // would land in a no-op default logger). Re-emitting from
            // here — after every plugin's setup hook has fired —
            // ensures the line lands in the freshly-opened log file.
            if let Some(rotation) = log_rotation::outcome() {
                let archived = rotation
                    .archived
                    .as_ref()
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|| "none".to_string());
                log::info!(
                    target: "startup",
                    "[startup] phase=log-rotated archived={archived} pruned_count={} errors={}",
                    rotation.pruned.len(),
                    rotation.errors.len()
                );
                for err in &rotation.errors {
                    log::warn!(target: "startup", "[startup] log-rotator error: {err}");
                }
            }

            // Parse CLI args: support --folder <path> and --file <path> flags
            let raw_args: Vec<String> = std::env::args().skip(1).collect();
            let cwd = std::env::current_dir().unwrap_or_default();
            let launch_args = parse_launch_args(&raw_args, &cwd);

            // Register the default "main" window in the registry.
            // Use canonicalize_no_verbatim consistently (not std::fs::canonicalize)
            // to avoid \\?\ mismatches on Windows (issue #248).
            let reg = app.state::<registry::WindowRegistry>();
            let first_canonical = launch_args.folders.first().and_then(|f| {
                crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(f)).ok()
            });
            if let Some(ref canonical) = first_canonical {
                reg.register("main".to_string(), registry::WindowKind::Folder(canonical.clone()));
            } else {
                reg.register("main".to_string(), registry::WindowKind::FileOnly);
            }

            // Create additional windows for extra folders (beyond the first),
            // deduplicating via route_folder() to enforce one-folder-one-window.
            let app_handle = app.handle().clone();
            for folder in launch_args.folders.iter().skip(1) {
                let canonical = match crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(folder)) {
                    Ok(c) => c,
                    Err(_) => std::path::PathBuf::from(folder),
                };
                match reg.route_folder(&canonical) {
                    registry::RouteDecision::FocusExisting(label) => {
                        log::info!("[window] setup: folder {} already open in {label}, skipping", canonical.display());
                    }
                    registry::RouteDecision::CreateFolder { path } => {
                        let label = reg.next_label();
                        let display = folder_display_name(&path);
                        match create_app_window(&app_handle, &label, &format!("mdownreview — {display}")) {
                            Ok(new_win) => {
                                reg.register(label.clone(), registry::WindowKind::Folder(path.clone()));
                                reg.push_args(&label, LaunchArgs {
                                    folders: vec![path.to_string_lossy().into_owned()],
                                    files: vec![],
                                });
                                let _ = new_win.emit("args-received", ());
                                log::info!("[window] setup: created {label} for {}", path.display());
                            }
                            Err(e) => log::error!("[window] setup: window for {} failed: {e}", path.display()),
                        }
                    }
                    _ => {}
                }
            }

            // Push args for the main window (first folder + all files);
            // the window's React will drain via get_launch_args on boot.
            let main_args = LaunchArgs {
                files: launch_args.files,
                folders: launch_args.folders.into_iter().take(1).collect(),
            };
            reg.push_args("main", main_args);

            // ── Per-window menu for main window ──────────────────────────────
            // Main window is created by tauri.conf.json; set its menu here.
            // The presence of the main webview window at this point is the
            // best in-process signal that the renderer is loadable, so we
            // record `WebviewReady` here. Frontend-side phases
            // (`ThemeApplied`, `FrontendMounted`, `FirstFileLoaded`) are
            // reported via `record_startup_phase` once React mounts.
            if let Some(main_win) = app.get_webview_window("main") {
                let main_menu = build_window_menu(app, "main")?;
                main_win.set_menu(main_menu)?;
                startup_recorder::record_phase(startup_recorder::StartupPhase::WebviewReady);
            }

            // ── Menu event routing ───────────────────────────────────────────
            // Menu item IDs encode the originating window as `{label}:{action}`
            // (per rule `multiwin-per-window-menu`). All IDs are window-scoped.
            app.on_menu_event(|app, event| {
                let id = event.id().as_ref();

                // Window-scoped actions: parse `{label}:{action}` from the menu item ID.
                let Some((label, action)) = parse_menu_id(id) else {
                    return;
                };
                let Some(window) = app.get_webview_window(label) else {
                    log::warn!("[menu] no window for label {label:?} (action {action:?})");
                    return;
                };

                // Rust-handled actions
                if action == "win-minimize" {
                    let _ = window.minimize();
                    return;
                }
                if action == "win-bring-all" {
                    for w in app.webview_windows().values() {
                        let _ = w.unminimize();
                        let _ = w.show();
                    }
                    return;
                }
                if action == "new-window" {
                    if let Err(e) = open_new_window(app) {
                        log::error!("[window] new-window failed: {e}");
                    }
                    return;
                }
                if action == "toggle-devtools" {
                    // Per-window devtools toggle. Available in release thanks
                    // to the `devtools` feature on `tauri` in Cargo.toml.
                    if window.is_devtools_open() {
                        window.close_devtools();
                    } else {
                        window.open_devtools();
                    }
                    return;
                }

                // Forward to the correct window as a frontend Tauri event
                let event_name = match action {
                    "open-file" => "menu-open-file",
                    "open-folder" => "menu-open-folder",
                    "close-folder" => "menu-close-folder",
                    "close-tab" => "menu-close-tab",
                    "close-all-tabs" => "menu-close-all-tabs",
                    "toggle-comments-pane" => "menu-toggle-comments-pane",
                    "next-tab" => "menu-next-tab",
                    "prev-tab" => "menu-prev-tab",
                    "theme-system" => "menu-theme-system",
                    "theme-light" => "menu-theme-light",
                    "theme-dark" => "menu-theme-dark",
                    "about" => "menu-about",
                    "check-updates" => "menu-check-updates",
                    "help-settings" => "menu-help-settings",
                    _ => return,
                };
                let _ = window.emit(event_name, ());
            });

            // Start file watcher
            watcher::start_watcher(app.handle());

            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::Destroyed = event {
                let label = window.label().to_string();
                if let Some(reg) = window.try_state::<registry::WindowRegistry>() {
                    reg.unregister(&label);
                    log::info!(
                        "[window] Destroyed: {label} — unregistered from WindowRegistry"
                    );
                }
                if let Some(ws) = window.try_state::<watcher::WatcherState>() {
                    ws.remove_window(&label);
                    log::info!("[window] Destroyed: {label} — removed from WatcherState");
                }
            }
        });

    // tauri-specta: build the typed command registry. With
    // `--features codegen` in debug builds, also export `src/lib/bindings.ts`
    // so the frontend's typed wrappers stay in lockstep with the Rust IPC
    // surface (issue #263). Path is relative to the cargo manifest dir
    // (i.e. src-tauri/). The feature gate keeps `specta-typescript` out of
    // production builds (Lean pillar in `docs/principles.md`).
    let specta_builder = build_specta_builder();

    #[cfg(all(debug_assertions, feature = "codegen"))]
    {
        // BigIntExportBehavior::Number: emit `number` for u64/i64 fields
        // (e.g. FileStat.size_bytes). Matches the existing TS hand-mirror;
        // markdown-review files are far below JS's 2^53 safe-integer cap,
        // so precision loss is theoretical. The same setting is applied in
        // `tests/specta_codegen.rs` so both export paths produce identical
        // output (no header/BigInt drift).
        if let Err(e) = specta_builder.export(
            Typescript::default()
                .header(BINDINGS_HEADER)
                .bigint(BigIntExportBehavior::Number),
            "../src/lib/bindings.ts",
        ) {
            eprintln!("[specta] failed to export bindings.ts: {e:?}");
            log::error!("[specta] failed to export bindings.ts: {e}");
        }
        // Windows-host regeneration affordance (issue #263): when
        // `MDOWNREVIEW_GEN_BINDINGS_ONLY` is set, exit BEFORE building the
        // tauri app. The codegen test in `tests/specta_codegen.rs` cannot
        // run on Windows dev hosts whose loader fails on webview2 import
        // tables (STATUS_ENTRYPOINT_NOT_FOUND); this path lets devs do
        // `MDOWNREVIEW_GEN_BINDINGS_ONLY=1 cargo run --features codegen` instead.
        if std::env::var_os("MDOWNREVIEW_GEN_BINDINGS_ONLY").is_some() {
            eprintln!("[specta] MDOWNREVIEW_GEN_BINDINGS_ONLY set — bindings emitted, exiting.");
            std::process::exit(0);
        }
    }

    // `fetch_remote_asset` returns `tauri::ipc::Response` (binary IPC) which
    // specta cannot describe. Compose its `tauri::generate_handler!` with
    // `specta_builder.invoke_handler()` into a single dispatcher closure
    // (each `tauri::Builder::invoke_handler` REPLACES, not chains, so we
    // route Invoke through specta first and fall through to the legacy
    // handler otherwise). Iter 2 may revisit by wrapping `fetch_remote_asset`
    // in a `Vec<u8>` return that specta can describe.
    let specta_handler = specta_builder.invoke_handler();
    let legacy_handler: Box<dyn Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync> =
        Box::new(tauri::generate_handler![
            commands::remote_asset::fetch_remote_asset
        ]);

    let app = app
        .invoke_handler(move |invoke| {
            if invoke.message.command() == "fetch_remote_asset" {
                legacy_handler(invoke)
            } else {
                specta_handler(invoke)
            }
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    // macOS / iOS: handle "Open With" file URLs via RunEvent::Opened.
    // on_url_open() was removed in Tauri 2.x; RunEvent::Opened is the replacement.
    app.run(|app_handle, event| {
        #[cfg(any(target_os = "macos", target_os = "ios"))]
        if let tauri::RunEvent::Opened { urls } = &event {
            let mut files = Vec::new();
            let mut folders = Vec::new();
            for url in urls {
                if let Ok(path) = url.to_file_path() {
                    let path_str = path.to_string_lossy().into_owned();
                    match std::fs::metadata(&path_str) {
                        Ok(meta) if meta.is_dir() => folders.push(path_str),
                        Ok(_) => files.push(path_str),
                        Err(_) => {}
                    }
                }
            }
            if !files.is_empty() || !folders.is_empty() {
                let args = LaunchArgs { files, folders };
                route_args_through_registry(app_handle, &args, "macOS-open");
            }
        }
        let _ = (app_handle, event);
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn folder_display_name_uses_last_component() {
        assert_eq!(folder_display_name(Path::new("/projects/myapp")), "myapp");
    }

    #[test]
    fn folder_display_name_root_path() {
        let name = folder_display_name(Path::new("/"));
        assert!(!name.is_empty());
    }

    #[cfg(windows)]
    #[test]
    fn folder_display_name_windows_path() {
        assert_eq!(
            folder_display_name(Path::new("C:\\Users\\Dev\\Project")),
            "Project"
        );
    }

    #[test]
    fn folder_display_name_trailing_separator() {
        let name = folder_display_name(Path::new("/projects/myapp/"));
        assert_eq!(name, "myapp");
    }

    #[test]
    fn encode_menu_id_format() {
        assert_eq!(encode_menu_id("main", "open-file"), "main:open-file");
        assert_eq!(encode_menu_id("win-1", "about"), "win-1:about");
    }

    #[test]
    fn parse_menu_id_window_scoped() {
        assert_eq!(parse_menu_id("main:open-file"), Some(("main", "open-file")));
        assert_eq!(parse_menu_id("win-42:theme-dark"), Some(("win-42", "theme-dark")));
    }

    #[test]
    fn parse_menu_id_global_returns_none() {
        assert_eq!(parse_menu_id("new-window"), None);
        assert_eq!(parse_menu_id("win-bring-all"), None);
    }

    #[test]
    fn parse_menu_id_first_colon_wins() {
        assert_eq!(parse_menu_id("win-1:some:action"), Some(("win-1", "some:action")));
    }
}
