// Self-alias so the `#[mdr_command]` proc-macro (in `mdr-macros/`) can
// emit absolute paths like `::mdown_review_lib::startup_recorder::…`
// uniformly — both INSIDE this crate's compile units AND in downstream
// integration tests. Without this, a bare `::mdown_review_lib::…` path
// inside `lib.rs` itself fails E0433 because the crate cannot
// self-reference by name. This is the canonical Rust pattern for
// proc-macros that need an absolute path back to the host crate.
extern crate self as mdown_review_lib;

pub mod commands;
pub mod core;
pub mod instance_scope;
pub mod launch_routing;
pub mod log_rotation;
pub mod macros;
pub mod menu;
pub mod registry;
pub mod startup_recorder;
pub mod tracing_log_bridge;
pub mod update;
pub mod watcher;
pub mod window_scope;

// Re-export `#[mdr_command]` at the crate root so call sites read
// `use crate::mdr_command;` (or `use mdown_review_lib::mdr_command;`
// from tests) instead of the deeper `crate::macros::mdr_command`.
// See `macros/mod.rs` for the indirection rationale.
pub use macros::mdr_command;

use commands::{parse_launch_args, LaunchArgs};
#[cfg(all(debug_assertions, feature = "codegen"))]
use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri::menu::{Menu, MenuBuilder, MenuItem, SubmenuBuilder};
use tauri::utils::config::Color;
use tauri::{Emitter, Manager, Runtime};
use tauri_plugin_log::{Target, TargetKind};

/// Default window background color — #0d1117. Painted by the OS BEFORE
/// WebView2 attaches, so a dark-theme cold start does not flash white.
/// See PR #265 for the FOUC analysis. Applied to every window (main and
/// secondary) via `WebviewWindowBuilder::background_color`; previously
/// lived in `tauri.conf.json::app.windows[0].backgroundColor`, but moved
/// to Rust when the main window's menu attachment forced programmatic
/// construction (otherwise the menu attaches post-show, causing a
/// client-rect reflow / re-render — the whole point of this refactor).
const WINDOW_BG: Color = Color(0x0d, 0x11, 0x17, 0xff);

// ---------------------------------------------------------------------------
// Single source of truth for the bindings.ts header literal. Both the
// runtime export path (this file's `run()` debug block) and the test export
// path (`tests/specta_codegen.rs::generate_bindings_ts`) reference this
// constant so the two cannot drift. iter-3's drift gate compares the file
// produced by EACH path against the committed `src/lib/bindings.ts`; if the
// headers diverged, every PR after one of the two ran would show a diff.
// ---------------------------------------------------------------------------

/// Header prepended to `src/lib/bindings.ts`. Kept in lockstep with both
/// the runtime export (in `run()` below) and the codegen test.
pub const BINDINGS_HEADER: &str = "/* eslint-disable */\n// @ts-nocheck\n// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n// Source: src-tauri/src/lib.rs::build_specta_builder.\n// Regenerate (Linux/macOS): `cd src-tauri && cargo test --features codegen --test specta_codegen generate_bindings_ts`.\n// Regenerate (Windows):     `cd src-tauri && MDOWNREVIEW_GEN_BINDINGS_ONLY=1 cargo run --features codegen`.\n\n";

// ---------------------------------------------------------------------------
// Multi-window helpers
// ---------------------------------------------------------------------------

/// Raise and focus a window (un-minimize → show → set-focus).
pub(crate) fn focus_window(win: &tauri::WebviewWindow) {
    let _ = win.unminimize();
    let _ = win.show();
    let _ = win.set_focus();
}

/// Extract a human-readable name from a path (last component, or full path).
pub(crate) fn folder_display_name(path: &std::path::Path) -> String {
    path.file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_else(|| path.to_string_lossy().into_owned())
}

// ---------------------------------------------------------------------------
// Per-window menu: encode window label into each menu item ID so
// on_menu_event can route to the correct originating window.
// See rule `multiwin-per-window-menu` in docs/best-practices-common/tauri/v2-patterns.md.
// ---------------------------------------------------------------------------

/// Encode a menu item ID as `{window_label}:{action}`.
fn encode_menu_id(label: &str, action: &str) -> String {
    format!("{label}:{action}")
}

/// Parse a menu item ID back into `(window_label, action)`.
/// Returns `None` for un-prefixed global IDs (e.g. "new-window").
fn parse_menu_id(id: &str) -> Option<(&str, &str)> {
    id.split_once(':')
}

/// Build the application menu.
///
/// On Windows/Linux this is built once per window (each window's menu bar is
/// independent) and `label` identifies the owning window in the menu IDs so
/// `on_menu_event` routes to that exact window.
///
/// On macOS the menu bar is **app-wide** — `Window::set_menu` is documented
/// as **Unsupported** on macOS, and the menu must be installed via
/// `AppHandle::set_menu`. We still build with `label = "main"` and keep the
/// `{label}:{action}` ID encoding for symmetry, but `on_menu_event` resolves
/// to the focused window on macOS rather than the encoded label.
///
/// On macOS the menu bar follows Apple conventions:
///   App (About · Settings · Services · Hide/Show · Quit) │ File │ Edit │ View │ Window │ Help
/// On Windows the layout is unchanged from the pre-macOS-support era:
///   File (incl. Settings · Quit) │ View │ Window │ Help (incl. About)
///
/// PredefinedMenuItems (About, Edit shortcuts, Services, Hide, Quit) are
/// OS-handled and never fire through `on_menu_event`; custom MenuItems keep
/// the `{label}:{action}` encoding.
fn build_window_menu<R: Runtime, M: Manager<R>>(
    handle: &M,
    label: &str,
) -> tauri::Result<Menu<R>> {
    let id = |action: &str| encode_menu_id(label, action);

    // ── Items shared across platforms ────────────────────────────────────
    let new_window = MenuItem::with_id(handle, id("new-window"), "New Window", true, None::<&str>)?;
    let open_file =
        MenuItem::with_id(handle, id("open-file"), "Open File…", true, Some("CmdOrCtrl+O"))?;
    let open_folder = MenuItem::with_id(
        handle, id("open-folder"), "Open Folder…", true, Some("CmdOrCtrl+Shift+O"),
    )?;
    let close_folder =
        MenuItem::with_id(handle, id("close-folder"), "Close Folder", true, None::<&str>)?;
    let close_tab =
        MenuItem::with_id(handle, id("close-tab"), "Close Tab", true, Some("CmdOrCtrl+W"))?;
    let close_all_tabs = MenuItem::with_id(
        handle, id("close-all-tabs"), "Close All Tabs", true, Some("CmdOrCtrl+Shift+W"),
    )?;
    // macOS HIG mandates Cmd+, for Settings (rule `mac-menu-settings-placement`
    // in docs/best-practices-common/tauri/macos-platform.md); on Windows the
    // accelerator is intentionally omitted — we don't reserve Ctrl+, globally.
    #[cfg(target_os = "macos")]
    let help_settings = MenuItem::with_id(handle, id("help-settings"), "Settings…", true, Some("CmdOrCtrl+,"))?;
    #[cfg(not(target_os = "macos"))]
    let help_settings = MenuItem::with_id(handle, id("help-settings"), "Settings…", true, None::<&str>)?;

    let toggle_comments_pane = MenuItem::with_id(
        handle, id("toggle-comments-pane"), "Toggle Comments Pane", true, Some("CmdOrCtrl+Shift+C"),
    )?;
    let next_tab = MenuItem::with_id(handle, id("next-tab"), "Next Tab", true, None::<&str>)?;
    let prev_tab = MenuItem::with_id(handle, id("prev-tab"), "Previous Tab", true, None::<&str>)?;
    let theme_system = MenuItem::with_id(handle, id("theme-system"), "System Theme", true, None::<&str>)?;
    let theme_light = MenuItem::with_id(handle, id("theme-light"), "Light Theme", true, None::<&str>)?;
    let theme_dark = MenuItem::with_id(handle, id("theme-dark"), "Dark Theme", true, None::<&str>)?;
    let theme_menu = SubmenuBuilder::new(handle, "Theme")
        .item(&theme_system).item(&theme_light).item(&theme_dark).build()?;
    let view_menu = SubmenuBuilder::new(handle, "View")
        .item(&toggle_comments_pane).separator()
        .item(&next_tab).item(&prev_tab).separator()
        .item(&theme_menu).build()?;

    let check_updates = MenuItem::with_id(handle, id("check-updates"), "Check for Updates…", true, None::<&str>)?;

    // Developer Tools — available in BOTH debug and release builds via the
    // `devtools` Cargo feature (see Cargo.toml). F12 is the cross-platform
    // accelerator. Rust-handled in `on_menu_event`.
    let toggle_devtools = MenuItem::with_id(
        handle, id("toggle-devtools"), "Toggle Developer Tools", true, Some("F12"),
    )?;

    // ── macOS menu bar ──────────────────────────────────────────────────
    // Rule mac-menu-app-submenu-first: first submenu is the app menu.
    // Rule mac-menu-edit-submenu / mac-webview-clipboard-requires-edit-menu:
    //   Edit menu enables Cmd+C/V/X in WKWebView inputs.
    // Rule mac-menu-no-quit-in-file: Quit is in the app menu, not File.
    // Rule mac-menu-settings-placement: Settings is in the app menu.
    // Rule mac-menu-window-submenu: Window has Minimize + Zoom.
    #[cfg(target_os = "macos")]
    {
        let app_menu = SubmenuBuilder::new(handle, "mdownreview")
            .about(None)
            .separator()
            .item(&help_settings)
            .separator()
            .services()
            .separator()
            .hide()
            .hide_others()
            .show_all()
            .separator()
            .quit()
            .build()?;

        let file_menu = SubmenuBuilder::new(handle, "File")
            .item(&new_window)
            .separator()
            .item(&open_file)
            .item(&open_folder)
            .item(&close_folder)
            .separator()
            .item(&close_tab)
            .item(&close_all_tabs)
            .build()?;

        let edit_menu = SubmenuBuilder::new(handle, "Edit")
            .undo()
            .redo()
            .separator()
            .cut()
            .copy()
            .paste()
            .select_all()
            .build()?;

        let win_bring_all = MenuItem::with_id(handle, id("win-bring-all"), "Bring All to Front", true, None::<&str>)?;
        let window_menu = SubmenuBuilder::new(handle, "Window")
            .minimize()
            .maximize()
            .separator()
            .item(&win_bring_all)
            .separator()
            .item(&toggle_devtools)
            .build()?;

        let help_menu = SubmenuBuilder::new(handle, "Help")
            .item(&check_updates)
            .build()?;

        return MenuBuilder::new(handle)
            .item(&app_menu)
            .item(&file_menu)
            .item(&edit_menu)
            .item(&view_menu)
            .item(&window_menu)
            .item(&help_menu)
            .build();
    }

    // ── Windows menu bar (unchanged from pre-macOS-support) ─────────────
    #[cfg(not(target_os = "macos"))]
    {
        let file_menu = SubmenuBuilder::new(handle, "File")
            .item(&new_window)
            .separator()
            .item(&open_file)
            .item(&open_folder)
            .item(&close_folder)
            .separator()
            .item(&close_tab)
            .item(&close_all_tabs)
            .separator()
            .item(&help_settings)
            .separator()
            .quit()
            .build()?;

        // "Bring All to Front" is a macOS-only Window-menu convention
        // (Apple HIG); on Windows the equivalent affordance is the
        // taskbar group thumbnail, so we omit it here.
        let win_minimize = MenuItem::with_id(handle, id("win-minimize"), "Minimize", true, None::<&str>)?;
        let window_menu = SubmenuBuilder::new(handle, "Window")
            .item(&win_minimize)
            .separator().item(&toggle_devtools).build()?;

        let about_item = MenuItem::with_id(handle, id("about"), "About mdownreview", true, None::<&str>)?;
        let help_menu = SubmenuBuilder::new(handle, "Help")
            .item(&check_updates).separator().item(&about_item).build()?;

        MenuBuilder::new(handle)
            .item(&file_menu).item(&view_menu).item(&window_menu).item(&help_menu)
            .build()
    }
}

/// Create a new application window.
///
/// On Windows the window gets its own menu via `WebviewWindowBuilder.menu()`.
/// On macOS the menu bar is app-wide (set once in `setup()` via
/// `AppHandle::set_menu`) so we deliberately do NOT call `.menu()` here —
/// `Window::set_menu` and `WindowBuilder::menu` are documented no-ops on
/// macOS (tauri::window::Window::set_menu rustdoc) and would just allocate a
/// menu that never gets attached.
pub(crate) fn create_app_window(
    handle: &tauri::AppHandle,
    label: &str,
    title: &str,
) -> tauri::Result<tauri::WebviewWindow> {
    let builder =
        tauri::WebviewWindowBuilder::new(handle, label, tauri::WebviewUrl::App("index.html".into()))
            .title(title)
            .inner_size(1100.0, 750.0)
            .min_inner_size(600.0, 400.0)
            .background_color(WINDOW_BG);

    #[cfg(not(target_os = "macos"))]
    let builder = {
        let menu = build_window_menu(handle, label)?;
        builder.menu(menu)
    };

    builder.build()
}

/// Build the main window programmatically with its menu pre-attached
/// (Windows/Linux) or with the menu installed app-wide via
/// `AppHandle::set_menu` after build (macOS — see setup()).
///
/// Why not declare it in `tauri.conf.json` like a normal Tauri app?
/// Because Tauri auto-creates config-declared windows BEFORE `setup()`
/// runs, and there is no `WindowConfig::menu` field — menus must be built
/// from a `Manager` handle. Calling `Window::set_menu` after the window
/// is shown installs the native HMENU on a visible window, which on
/// Windows shrinks the WebView2 client rect by the menu-bar height,
/// firing `WM_SIZE` → resize observers → an unnecessary React re-render
/// during cold start. Building the window here, with `.menu(menu)`
/// before `.build()` on Windows/Linux, attaches the menu before the
/// first paint so the WebView2 client rect is correct from the start.
///
/// On macOS, `WindowBuilder::menu` is a documented no-op (the menu bar
/// belongs to NSApp, not NSWindow), so we skip `.menu()` here and let
/// setup() install the global menu via `AppHandle::set_menu` instead.
/// macOS does not exhibit the Windows HMENU client-rect-shrink behavior,
/// so the post-build app.set_menu path is flicker-free there.
///
/// Sizes mirror the previous `tauri.conf.json::app.windows[0]` block.
/// The `WINDOW_BG` constant preserves PR #265's cold-start FOUC fix.
fn build_main_window(handle: &tauri::AppHandle) -> tauri::Result<tauri::WebviewWindow> {
    let builder =
        tauri::WebviewWindowBuilder::new(handle, "main", tauri::WebviewUrl::App("index.html".into()))
            .title("mdownreview")
            .inner_size(1200.0, 800.0)
            .min_inner_size(800.0, 600.0)
            .background_color(WINDOW_BG);

    #[cfg(not(target_os = "macos"))]
    let builder = {
        let menu = build_window_menu(handle, "main")?;
        builder.menu(menu)
    };

    builder.build()
}

/// Shared logic for opening a new empty window. Used by the native menu handler.
fn open_new_window(app: &tauri::AppHandle) -> Result<(), String> {
    let reg = app.state::<registry::WindowRegistry>();
    let new_label = reg.next_label();
    create_app_window(app, &new_label, "mdownreview")
        .map(|_| {
            reg.register(new_label.clone(), registry::WindowKind::FileOnly);
            // Issue #338 / Group A foundation: every `WindowRegistry::register`
            // site routes through `window_scope::extend_window_scope` so the
            // chokepoint discipline is structural, not customary. Empty FileOnly
            // windows have no files to grant scope for — the call is a
            // documented no-op for this variant — but skipping it would
            // normalise the bypass for future maintainers.
            window_scope::extend_window_scope(app, &new_label, &registry::WindowKind::FileOnly, &[]);
            log::info!("[window] new-window: created {new_label}");
        })
        .map_err(|e| format!("failed to create window: {e}"))
}

#[mdr_command]
fn register_window_folder(
    window: tauri::Window,
    folder: String,
    registry: tauri::State<'_, registry::WindowRegistry>,
) -> Result<(), String> {
    let canonical = crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(&folder))
        .map_err(|e| format!("invalid folder: {}", e))?;
    let display = folder_display_name(&canonical);
    match registry.try_claim_folder(window.label(), canonical.clone()) {
        Ok(()) => {
            let _ = window.set_title(&format!("mdownreview — {display}"));
            // #338 iter-1 forward-fix: chokepoint asset-scope + watcher seed.
            window_scope::extend_window_scope(
                window.app_handle(),
                window.label(),
                &registry::WindowKind::Folder(canonical.clone()),
                &[],
            );
            log::info!("[window] {} registered folder: {display}", window.label());
            Ok(())
        }
        Err(existing_label) => {
            // Focus the window that already owns this folder
            if let Some(existing_win) = window.app_handle().get_webview_window(&existing_label) {
                focus_window(&existing_win);
            }
            log::info!(
                "[window] {} tried to claim folder {display} already owned by {existing_label}",
                window.label()
            );
            Err(format!("folder already open in window '{existing_label}'"))
        }
    }
}

#[mdr_command]
fn unregister_window_folder(
    window: tauri::Window,
    registry: tauri::State<'_, registry::WindowRegistry>,
) -> Result<(), String> {
    registry.update_kind(window.label(), registry::WindowKind::FileOnly);
    let _ = window.set_title("mdownreview");
    log::info!("[window] {} unregistered folder", window.label());
    Ok(())
}

// Route incoming `LaunchArgs` through the `WindowRegistry` — extracted to
// `launch_routing.rs` to keep `lib.rs` under the file-size budget (rule 23
// of `docs/architecture.md`). Shared by single-instance, `setup()`, and
// `RunEvent::Opened`.
use launch_routing::route_args_through_registry;

/// Build the `tauri_specta::Builder` carrying every IPC command.
///
/// The 41-command stable list is declared exactly ONCE inside the
/// `specta_commands!` `macro_rules!` below. Debug builds append
/// `set_root_via_test` (used only by the native e2e harness); release
/// builds get the empty extras list. The textual list never appears
/// twice in the source, satisfying the Never-Increase-Debt principle
/// (`docs/principles.md`) and rule 23 file-size budget in
/// `docs/architecture.md`.
///
/// The returned builder owns the command registry; its `.invoke_handler()`
/// REPLACES the previous `tauri::generate_handler![]` call. In debug
/// builds with `--features codegen`, [`pub fn run`] also calls `.export()`
/// on this builder to emit `src/lib/bindings.ts` (issue #263).
///
/// `commands::remote_asset::fetch_remote_asset` is NOT registered here —
/// it returns a `tauri::ipc::Response` (binary IPC) that specta cannot
/// describe. It is registered separately via the merge pattern below.
/// Iter 2 may revisit.
pub fn build_specta_builder() -> tauri_specta::Builder<tauri::Wry> {
    // The inner `tauri_specta::collect_commands!` is a `macro_rules!`
    // taking a comma-separated list of paths (with optional turbofish
    // generics). We splat `$($extra:tt)*` raw into the tail; an empty
    // splat just leaves the trailing comma after `unregister_window_folder`,
    // which `collect_commands!`'s `$(,)?` accepts.
    macro_rules! specta_commands {
        ($($extra:tt)*) => {
            tauri_specta::collect_commands![
                commands::fs::dir::read_dir,
                commands::fs::read::read_text_file,
                commands::fs::read::read_binary_file,
                commands::fs::stat_file,
                commands::system::reveal_in_folder,
                commands::html::resolve_html_assets,
                commands::launch::get_launch_args,
                commands::launch::get_log_path,
                commands::launch::scan_review_files,
                commands::fs::check_path_exists,
                commands::fs::canonicalize_path,
                commands::fs_write::write_workspace_text,
                commands::fs_write::write_workspace_binary,
                commands::close_flush::close_flush_complete,
                commands::close_flush::mark_close_flush_ready,
                commands::open_file_registry::claim_open_file,
                commands::open_file_registry::release_open_file,
                commands::open_file_registry::release_open_files,
                commands::comments::get::get_file_comments,
                commands::comments::add_comment::<tauri::Wry>,
                commands::comments::add_reply::<tauri::Wry>,
                commands::comments::edit_comment::<tauri::Wry>,
                commands::comments::delete_comment::<tauri::Wry>,
                commands::comments::compute_anchor_hash,
                commands::comments::update::update_comment::<tauri::Wry>,
                commands::comments::badges::get_file_badges,
                commands::config::set_author,
                commands::config::get_author,
                commands::search::search_in_document,
                commands::html::compute_fold_regions,
                commands::search::parse_kql,
                commands::search::strip_json_comments,
                commands::onboarding::onboarding_state,
                commands::cli_shim::cli_shim_status,
                commands::cli_shim::install_cli_shim,
                commands::cli_shim::remove_cli_shim,
                commands::default_handler::default_handler_status,
                commands::default_handler::set_default_handler,
                commands::file_viewer_prefs::get_file_viewer_pref,
                commands::file_viewer_prefs::set_file_viewer_pref,
                watcher::update_watched_files,
                commands::fs::update_tree_watched_dirs,
                commands::word_tokens::tokenize_words,
                commands::path_classify::path_classify,
                commands::sidecar_config::get_sidecar_config,
                commands::sidecar_config::set_sidecar_config,
                commands::sidecar_config::migrate_sidecars_cmd,
                commands::startup::record_startup_phase,
                update::check_update,
                update::install_update,
                register_window_folder,
                unregister_window_folder,
                $($extra)*
            ]
        };
    }

    #[cfg(debug_assertions)]
    {
        tauri_specta::Builder::<tauri::Wry>::new()
            .commands(specta_commands![commands::launch::set_root_via_test])
    }
    #[cfg(not(debug_assertions))]
    {
        tauri_specta::Builder::<tauri::Wry>::new().commands(specta_commands![])
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Anchor the StartupRecorder timeline. Touching `record_phase` here
    // also forces lazy `OnceLock` init so the `t_ms` baseline matches
    // the user-visible "process start" rather than the first IPC call.
    // See `startup_recorder` for the schema (`[startup] phase=app-init t_ms=…`).
    startup_recorder::record_phase(startup_recorder::StartupPhase::AppInit);

    // Apply the IPC trace gate precedence chain BEFORE the Tauri builder
    // spins up the runtime (no IPC dispatches before `Builder::build()`
    // returns, so the gate is set before any `#[mdr_command]` call reads
    // it via `ipc_trace_enabled()`):
    //
    //   1. `--trace[=on|off]` launch flag  (highest)
    //   2. `MDR_IPC_TRACE` env var         (existing escape hatch)
    //   3. `cfg!(debug_assertions)`        (debug-on by default)
    //
    // See `docs/observability.md` for the user-facing description and
    // `commands::launch::parse_trace_flag` for accepted flag forms.
    let early_argv: Vec<String> = std::env::args().skip(1).collect();
    let trace_enabled = commands::launch::parse_trace_flag(&early_argv)
        .or_else(|| std::env::var("MDR_IPC_TRACE").ok().map(|_| true))
        .unwrap_or(cfg!(debug_assertions));
    startup_recorder::set_ipc_trace_enabled(trace_enabled);

    let log_plugin = {
        let mut builder = tauri_plugin_log::Builder::new()
            .max_file_size(5 * 1024 * 1024)
            .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepAll);

        #[cfg(debug_assertions)]
        {
            builder = builder.level(log::LevelFilter::Debug).targets([
                Target::new(TargetKind::Webview),
                Target::new(TargetKind::LogDir {
                    file_name: Some("mdownreview".to_string()),
                }),
                Target::new(TargetKind::Stdout),
            ]);
        }
        #[cfg(not(debug_assertions))]
        {
            builder = builder.level(log::LevelFilter::Info).targets([
                Target::new(TargetKind::Webview)
                    .filter(|metadata| metadata.level() <= log::Level::Warn),
                Target::new(TargetKind::LogDir {
                    file_name: Some("mdownreview".to_string()),
                }),
            ]);
        }

        builder.build()
    };

    // Install tracing → log bridge so the existing `tracing::*` call sites
    // throughout `commands/`, `core/`, and `watcher.rs` reach
    // `tauri-plugin-log` (without this, every structured `tracing::warn!`
    // is silently dropped — see `tracing_log_bridge` rustdoc for the
    // history). Must run BEFORE the first `tracing::*` call site fires; the
    // tauri builder below uses some `tracing::*` calls indirectly so we
    // install it as early as possible after building the log plugin.
    tracing_log_bridge::install();

    let (sync_tx, sync_rx) = std::sync::mpsc::sync_channel::<()>(1);

    let mut builder = tauri::Builder::default()
        // MUST precede log_plugin — the rotator's setup hook archives the
        // previous mdownreview.log + prunes to log_rotation::DEFAULT_KEEP
        // BEFORE tauri-plugin-log opens the file. See log_rotation.rs.
        .plugin(log_rotation::plugin())
        .plugin(log_plugin)
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_clipboard_manager::init());

    // Production builds enforce single-instance; debug/test-isolated builds
    // skip it so multiple instances can coexist (AC 7 of #147).
    if !instance_scope::is_isolated() {
        builder = builder.plugin(tauri_plugin_single_instance::init(
            |app, argv, cwd| {
                let cwd_path = std::path::PathBuf::from(&cwd);
                let args = parse_launch_args(&argv[1..], &cwd_path);

                route_args_through_registry(app, &args, "single-instance");
            },
        ));
    }

    let app = builder
        .plugin(tauri_plugin_updater::Builder::new().build())
        // `plugin:process|restart` — invoked by `restartApp()` /
        // `@tauri-apps/plugin-process` `relaunch()` after the updater has
        // staged a new bundle. Must be registered or the "Restart Now"
        // button on the update banner is a no-op (unrouted IPC). See
        // capabilities/default.json for the matching `process:allow-restart`
        // ACL — least-privilege over `process:default` (which would also
        // grant `allow-exit`, a command we never invoke).
        .plugin(tauri_plugin_process::init())
        .manage(update::PendingUpdate(std::sync::Mutex::new(None)))
        .manage(watcher::WatcherState::new(sync_tx))
        .manage(watcher::SidecarConfigState::new())
        .manage(watcher::SyncRx(std::sync::Mutex::new(Some(sync_rx))))
        .manage(registry::WindowRegistry::default())
        .manage(commands::comments::BadgeCache::new())
        .manage(commands::close_flush::CloseFlushState::new())
        .manage(commands::open_file_registry::OpenFileRegistry::new())
        .setup(|app| {
            // Register panic hook to log panics before process terminates
            let prev_hook = std::panic::take_hook();
            std::panic::set_hook(Box::new(move |info| {
                let msg = info.payload().downcast_ref::<&str>().copied()
                    .or_else(|| info.payload().downcast_ref::<String>().map(|s| s.as_str()))
                    .unwrap_or("unknown panic");
                let loc = info.location()
                    .map(|l| format!(" at {}:{}", l.file(), l.line()))
                    .unwrap_or_default();
                log::error!("[rust] PANIC{loc}: {msg}");
                prev_hook(info);
            }));

            // Surface the log-rotator's outcome through the standard
            // logging chokepoint now that tauri-plugin-log is up. See
            // `log_rotation::surface_outcome` for the line schema.
            log_rotation::surface_outcome();

            // Parse CLI args: support --folder <path> and --file <path> flags
            let raw_args: Vec<String> = std::env::args().skip(1).collect();
            let cwd = std::env::current_dir().unwrap_or_default();
            let launch_args = parse_launch_args(&raw_args, &cwd);

            // Register the default "main" window in the registry.
            // Use canonicalize_no_verbatim consistently (not std::fs::canonicalize)
            // to avoid \\?\ mismatches on Windows (issue #248).
            let reg = app.state::<registry::WindowRegistry>();
            let first_canonical = launch_args.folders.first().and_then(|f| {
                crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(f)).ok()
            });
            if let Some(ref canonical) = first_canonical {
                reg.register("main".to_string(), registry::WindowKind::Folder(canonical.clone()));
                // #338 iter-1 forward-fix: extend asset-scope AND seed
                // tree-watched-dirs synchronously so the renderer's first
                // file-read IPC passes the workspace guard.
                window_scope::extend_window_scope(app.handle(), "main", &registry::WindowKind::Folder(canonical.clone()), &[]);
            } else {
                reg.register("main".to_string(), registry::WindowKind::FileOnly);
                let file_paths: Vec<std::path::PathBuf> = launch_args
                    .files
                    .iter()
                    .map(std::path::PathBuf::from)
                    .collect();
                window_scope::extend_window_scope(app.handle(), "main", &registry::WindowKind::FileOnly, &file_paths);
            }

            // Create additional windows for extra folders (beyond the first),
            // deduplicating via route_folder() to enforce one-folder-one-window.
            let app_handle = app.handle().clone();
            for folder in launch_args.folders.iter().skip(1) {
                let canonical = match crate::core::paths::canonicalize_no_verbatim(std::path::Path::new(folder)) {
                    Ok(c) => c,
                    Err(_) => std::path::PathBuf::from(folder),
                };
                match reg.route_folder(&canonical) {
                    registry::RouteDecision::FocusExisting(label) => {
                        log::info!("[window] setup: folder {} already open in {label}, skipping", canonical.display());
                    }
                    registry::RouteDecision::CreateFolder { path } => {
                        let label = reg.next_label();
                        let display = folder_display_name(&path);
                        match create_app_window(&app_handle, &label, &format!("mdownreview — {display}")) {
                            Ok(_new_win) => {
                                let kind = registry::WindowKind::Folder(path.clone());
                                reg.register(label.clone(), kind.clone());
                                // #338 iter-1 forward-fix: chokepoint asset-scope + watcher seed.
                                window_scope::extend_window_scope(&app_handle, &label, &kind, &[]);
                                reg.push_args(&label, LaunchArgs {
                                    folders: vec![path.to_string_lossy().into_owned()],
                                    files: vec![],
                                });
                                // Rule multiwin-window-scoped-events: AppHandle::emit_to.
                                let _ = app_handle.emit_to(&label, "args-received", ());
                                log::info!("[window] setup: created {label} for {}", path.display());
                            }
                            Err(e) => log::error!("[window] setup: window for {} failed: {e}", path.display()),
                        }
                    }
                    _ => {}
                }
            }

            // Push args for the main window (first folder + all files);
            // the window's React will drain via get_launch_args on boot.
            let main_args = LaunchArgs {
                files: launch_args.files,
                folders: launch_args.folders.into_iter().take(1).collect(),
            };
            reg.push_args("main", main_args);

            // ── Build the main window ────────────────────────────────────────
            // `tauri.conf.json` does NOT declare an `app.windows[]` entry — see
            // the comment on `build_main_window` for why the main window is
            // constructed here instead. On Windows/Linux, `.menu(menu)` is
            // chained into the builder so the HMENU is in place from the very
            // first attach and the WebView2 client rect never reflows post-show
            // (the original cold-start menu-area flicker bug).
            //
            // On macOS, `WindowBuilder::menu` is a no-op — the menu belongs to
            // NSApp, not NSWindow. `build_main_window` skips `.menu()` there
            // and we install the menu app-wide via `AppHandle::set_menu` after
            // build. macOS doesn't have the Windows HMENU client-rect-shrink
            // problem, so this post-build path is flicker-free.
            //
            // `push_args("main", …)` above runs BEFORE this build so pending
            // args are queued before React mounts and calls `get_launch_args`.
            build_main_window(app.handle())?;
            #[cfg(target_os = "macos")]
            {
                let main_menu = build_window_menu(app, "main")?;
                app.set_menu(main_menu)?;
            }
            // Record `WebviewReady` AFTER `.build()` (and the macOS app.set_menu)
            // returns successfully, so the phase bookmarks "user can see a stable
            // frame" rather than the (now-eliminated) post-show menu-attach
            // intermediate state. Frontend-side phases (`ThemeApplied`,
            // `FrontendMounted`, `FirstFileLoaded`) are reported via
            // `record_startup_phase` once React mounts.
            startup_recorder::record_phase(startup_recorder::StartupPhase::WebviewReady);

            // ── Menu event routing ───────────────────────────────────────────
            // Menu item IDs encode the originating window as `{label}:{action}`
            // (per rule `multiwin-per-window-menu`). On Windows/Linux the
            // encoded label IS the window that owns this menu bar. On macOS
            // the menu bar is global, so the encoded label ("main") is just a
            // placeholder — we resolve to the focused window so commands act
            // on whatever window the user is actually looking at.
            app.on_menu_event(|app, event| {
                let id = event.id().as_ref();
                log::info!("[menu] on_menu_event raw-id={id:?}");

                let Some((encoded_label, action)) = parse_menu_id(id) else {
                    log::info!("[menu] raw-id has no label prefix — ignoring");
                    return;
                };

                #[cfg(target_os = "macos")]
                let label_owned: String = app
                    .webview_windows()
                    .iter()
                    .find(|(_, w)| w.is_focused().unwrap_or(false))
                    .map(|(l, _)| l.clone())
                    .unwrap_or_else(|| encoded_label.to_string());
                #[cfg(target_os = "macos")]
                let label: &str = label_owned.as_str();
                #[cfg(not(target_os = "macos"))]
                let label: &str = encoded_label;

                log::info!(
                    "[menu] resolved encoded-label={encoded_label:?} \
                     firing-label={label:?} action={action:?}"
                );

                let Some(window) = app.get_webview_window(label) else {
                    log::warn!("[menu] no window for label {label:?} (action {action:?})");
                    return;
                };

                // Rust-handled actions
                if action == "win-minimize" {
                    let _ = window.minimize();
                    return;
                }
                if action == "win-bring-all" {
                    for w in app.webview_windows().values() {
                        // On macOS, skip windows hidden by the CloseRequested
                        // handler — "Bring All to Front" should not resurrect
                        // windows the user already closed.
                        if w.is_visible().unwrap_or(false) {
                            let _ = w.unminimize();
                        }
                    }
                    return;
                }
                if action == "new-window" {
                    if let Err(e) = open_new_window(app) {
                        log::error!("[window] new-window failed: {e}");
                    }
                    return;
                }
                if action == "toggle-devtools" {
                    // Per-window devtools toggle. Available in release thanks
                    // to the `devtools` feature on `tauri` in Cargo.toml.
                    if window.is_devtools_open() {
                        window.close_devtools();
                    } else {
                        window.open_devtools();
                    }
                    return;
                }

                // Forward to the correct window via the testable
                // `menu::dispatch_menu_event` seam (rule
                // `multiwin-window-scoped-events`). Tauri's
                // `Emitter::emit` broadcasts on every receiver, so the
                // dispatcher uses an explicit `MenuEmitter` trait that
                // distinguishes `emit_to(label, …)` from
                // `emit(…)` — integration tests mock the trait to
                // prove the right shape reaches the emitter even
                // though the call site uses a variable event name.
                let _ = menu::dispatch_menu_event(app, action, label);
            });

            // Start file watcher
            watcher::start_watcher(app.handle());

            Ok(())
        })
        .on_window_event(|window, event| {
            // Rule mac-lifecycle-close-hides: on macOS, closing the last
            // visible window hides it (app stays in Dock). Cmd+Q is the
            // only exit path. Non-last windows close normally.
            #[cfg(target_os = "macos")]
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let visible_count = window
                    .app_handle()
                    .webview_windows()
                    .values()
                    .filter(|w| w.is_visible().unwrap_or(false))
                    .count();
                if visible_count <= 1 {
                    api.prevent_close();
                    let _ = window.hide();
                    log::info!(
                        "[window] CloseRequested on {}: hidden (last visible window)",
                        window.label()
                    );
                    return;
                }
            }

            // Issue #352 / iter-12 (bug #4 — close-flush handshake).
            // Iter-16 — gate prevent_close on the renderer's mark-ready
            // signal AND use `window.destroy()` (not `close()`) on the
            // happy path so we definitively bypass any CloseRequested
            // re-entry hazard.
            //
            // If the renderer hasn't yet marked itself ready (cold
            // start before React mounts, crashed JS thread, no
            // Excalidraw editors and the hook hasn't committed),
            // skip the handshake entirely — Tauri closes immediately.
            // Eliminates the 2.5 s lag bug-expert flagged for
            // non-Excalidraw users and fast cold-close.
            //
            // If the renderer IS ready, drain its registry via the
            // ack handshake; on success/timeout, the spawned task
            // calls `window.destroy()`.
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                let label = window.label().to_string();
                let is_ready = window
                    .try_state::<commands::close_flush::CloseFlushState>()
                    .map(|s| s.is_ready(&label))
                    .unwrap_or(false);
                if !is_ready {
                    log::info!(
                        "[close-flush] {label} not ready — letting Tauri close normally"
                    );
                    return;
                }
                api.prevent_close();
                commands::close_flush::flush_pending_writes_before_close(
                    window.app_handle(),
                    label,
                );
                return;
            }

            if let tauri::WindowEvent::Destroyed = event {
                let label = window.label().to_string();
                if let Some(reg) = window.try_state::<registry::WindowRegistry>() {
                    reg.unregister(&label);
                    log::info!(
                        "[window] Destroyed: {label} — unregistered from WindowRegistry"
                    );
                }
                if let Some(ws) = window.try_state::<watcher::WatcherState>() {
                    ws.remove_window(&label);
                    log::info!("[window] Destroyed: {label} — removed from WatcherState");
                }
                // Iter-16 — drop close-flush ready/pending entries so
                // a recycled label doesn't carry stale state.
                if let Some(cfs) = window.try_state::<commands::close_flush::CloseFlushState>() {
                    cfs.forget_window(&label);
                    log::info!("[window] Destroyed: {label} — forgot CloseFlushState");
                }
                // Issue #352 / iter-15 — purge open-file claims owned
                // by the dying window so a force-killed renderer
                // (no clean release) doesn't leak entries that block
                // future opens of the same path in other windows.
                if let Some(ofr) = window.try_state::<commands::open_file_registry::OpenFileRegistry>() {
                    ofr.purge_window(&label);
                    log::info!("[window] Destroyed: {label} — purged OpenFileRegistry");
                }
            }
        });

    // tauri-specta: build the typed command registry. With
    // `--features codegen` in debug builds, also export `src/lib/bindings.ts`
    // so the frontend's typed wrappers stay in lockstep with the Rust IPC
    // surface (issue #263). Path is relative to the cargo manifest dir
    // (i.e. src-tauri/). The feature gate keeps `specta-typescript` out of
    // production builds (Lean pillar in `docs/principles.md`).
    let specta_builder = build_specta_builder();

    #[cfg(all(debug_assertions, feature = "codegen"))]
    {
        // BigIntExportBehavior::Number: emit `number` for u64/i64 fields
        // (e.g. FileStat.size_bytes). Matches the existing TS hand-mirror;
        // markdown-review files are far below JS's 2^53 safe-integer cap,
        // so precision loss is theoretical. The same setting is applied in
        // `tests/specta_codegen.rs` so both export paths produce identical
        // output (no header/BigInt drift).
        if let Err(e) = specta_builder.export(
            Typescript::default()
                .header(BINDINGS_HEADER)
                .bigint(BigIntExportBehavior::Number),
            "../src/lib/bindings.ts",
        ) {
            eprintln!("[specta] failed to export bindings.ts: {e:?}");
            log::error!("[specta] failed to export bindings.ts: {e}");
        }
        // Windows-host regeneration affordance (issue #263): when
        // `MDOWNREVIEW_GEN_BINDINGS_ONLY` is set, exit BEFORE building the
        // tauri app. The codegen test in `tests/specta_codegen.rs` cannot
        // run on Windows dev hosts whose loader fails on webview2 import
        // tables (STATUS_ENTRYPOINT_NOT_FOUND); this path lets devs do
        // `MDOWNREVIEW_GEN_BINDINGS_ONLY=1 cargo run --features codegen` instead.
        if std::env::var_os("MDOWNREVIEW_GEN_BINDINGS_ONLY").is_some() {
            eprintln!("[specta] MDOWNREVIEW_GEN_BINDINGS_ONLY set — bindings emitted, exiting.");
            std::process::exit(0);
        }
    }

    // `fetch_remote_asset` returns `tauri::ipc::Response` (binary IPC) which
    // specta cannot describe. Compose its `tauri::generate_handler!` with
    // `specta_builder.invoke_handler()` into a single dispatcher closure
    // (each `tauri::Builder::invoke_handler` REPLACES, not chains, so we
    // route Invoke through specta first and fall through to the legacy
    // handler otherwise). Iter 2 may revisit by wrapping `fetch_remote_asset`
    // in a `Vec<u8>` return that specta can describe.
    let specta_handler = specta_builder.invoke_handler();
    let legacy_handler: Box<dyn Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync> =
        Box::new(tauri::generate_handler![
            commands::remote_asset::fetch_remote_asset
        ]);

    let app = app
        .invoke_handler(move |invoke| {
            if invoke.message.command() == "fetch_remote_asset" {
                legacy_handler(invoke)
            } else {
                specta_handler(invoke)
            }
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application");

    // macOS / iOS: handle "Open With" file URLs via RunEvent::Opened.
    // on_url_open() was removed in Tauri 2.x; RunEvent::Opened is the replacement.
    app.run(|app_handle, event| {
        #[cfg(any(target_os = "macos", target_os = "ios"))]
        if let tauri::RunEvent::Opened { urls } = &event {
            let mut files = Vec::new();
            let mut folders = Vec::new();
            for url in urls {
                if let Ok(path) = url.to_file_path() {
                    let path_str = path.to_string_lossy().into_owned();
                    match std::fs::metadata(&path_str) {
                        Ok(meta) if meta.is_dir() => folders.push(path_str),
                        Ok(_) => files.push(path_str),
                        Err(_) => {}
                    }
                }
            }
            if !files.is_empty() || !folders.is_empty() {
                let args = LaunchArgs { files, folders };
                route_args_through_registry(app_handle, &args, "macOS-open");
            }
        }

        // Rule mac-lifecycle-reopen-on-activate: clicking the Dock icon
        // when all windows are hidden re-shows them.
        #[cfg(target_os = "macos")]
        if let tauri::RunEvent::Reopen {
            has_visible_windows, ..
        } = &event
        {
            if !has_visible_windows {
                let windows = app_handle.webview_windows();
                for win in windows.values() {
                    let _ = win.show();
                }
                // Focus main if it exists; otherwise focus any window.
                if let Some(win) = windows
                    .get("main")
                    .or_else(|| windows.values().next())
                {
                    let _ = win.set_focus();
                }
            }
        }

        // Iter-22 (#352 bug-expert iter-21 P2-4 / arch P0 on macOS) —
        // `RunEvent::ExitRequested` flush handshake.
        //
        // macOS Cmd+Q (and any other path that fires `ExitRequested`
        // BEFORE per-window `WindowEvent::CloseRequested`) silently
        // dropped up to `EXCALIDRAW_AUTOSAVE_DEBOUNCE_MS` of edits
        // pre-iter-22 because the close-flush handshake (in
        // `commands/close_flush.rs`) is keyed on `CloseRequested` only.
        // AGENTS.md lists macOS as a Tier-1 platform; shipping a
        // silent data-loss path on the most common Mac quit gesture
        // is a *Reliable* + *Professional* pillar regression.
        //
        // Strategy: prevent the exit, broadcast `flush-before-close`
        // to every ready window, wait up to `CLOSE_FLUSH_TIMEOUT_MS`
        // for the renderer drains to complete, then call
        // `app_handle.exit(0)`. Best-effort: if a window is not
        // ready (cold start, crashed JS) we still proceed to exit so
        // the user is not deadlocked. The wait ceiling matches the
        // CloseRequested handshake's per-window cap.
        if let tauri::RunEvent::ExitRequested { api, .. } = &event {
            let cfs = match app_handle.try_state::<commands::close_flush::CloseFlushState>() {
                Some(s) => s,
                None => {
                    // State not registered (cold start before setup);
                    // nothing to drain. Let the exit proceed.
                    return;
                }
            };
            let labels: Vec<String> = app_handle
                .webview_windows()
                .keys()
                .filter(|label| cfs.is_ready(label))
                .cloned()
                .collect();
            if labels.is_empty() {
                // No ready windows — no autosave editor open or all
                // crashed. Let exit proceed.
                return;
            }
            api.prevent_exit();
            log::info!(
                "[exit-flush] ExitRequested — draining {} ready window(s)",
                labels.len()
            );

            // Spawn the wait-and-exit task on Tauri's async runtime so
            // the synchronous RunEvent callback returns immediately.
            let app_handle_clone = app_handle.clone();
            tauri::async_runtime::spawn(async move {
                let drain = commands::close_flush::flush_all_for_exit(
                    app_handle_clone.clone(),
                    labels,
                );
                let timeout = std::time::Duration::from_millis(
                    commands::close_flush::CLOSE_FLUSH_TIMEOUT_MS,
                );
                match tokio::time::timeout(timeout, drain).await {
                    Ok(()) => log::info!(
                        "[exit-flush] all windows drained, exiting"
                    ),
                    Err(_) => log::warn!(
                        "[exit-flush] timeout ({}ms), forcing exit",
                        commands::close_flush::CLOSE_FLUSH_TIMEOUT_MS
                    ),
                }
                app_handle_clone.exit(0);
            });
        }

        let _ = (app_handle, event);
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn folder_display_name_uses_last_component() {
        assert_eq!(folder_display_name(Path::new("/projects/myapp")), "myapp");
    }

    #[test]
    fn folder_display_name_root_path() {
        let name = folder_display_name(Path::new("/"));
        assert!(!name.is_empty());
    }

    #[cfg(windows)]
    #[test]
    fn folder_display_name_windows_path() {
        assert_eq!(
            folder_display_name(Path::new("C:\\Users\\Dev\\Project")),
            "Project"
        );
    }

    #[test]
    fn folder_display_name_trailing_separator() {
        let name = folder_display_name(Path::new("/projects/myapp/"));
        assert_eq!(name, "myapp");
    }

    #[test]
    fn encode_menu_id_format() {
        assert_eq!(encode_menu_id("main", "open-file"), "main:open-file");
        assert_eq!(encode_menu_id("win-1", "about"), "win-1:about");
    }

    #[test]
    fn parse_menu_id_window_scoped() {
        assert_eq!(parse_menu_id("main:open-file"), Some(("main", "open-file")));
        assert_eq!(parse_menu_id("win-42:theme-dark"), Some(("win-42", "theme-dark")));
    }

    #[test]
    fn parse_menu_id_global_returns_none() {
        assert_eq!(parse_menu_id("new-window"), None);
        assert_eq!(parse_menu_id("win-bring-all"), None);
    }

    #[test]
    fn parse_menu_id_first_colon_wins() {
        assert_eq!(parse_menu_id("win-1:some:action"), Some(("win-1", "some:action")));
    }
}
